# Generated by Django 5.0.1 on 2026-02-14 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='adr',
            field=models.FloatField(blank=True, help_text='Adjusted Defensive Rating (pts/100 possessions)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='adr_100',
            field=models.FloatField(blank=True, help_text='ADR mapped to 0-100 scale (inverted: lower ADR = higher rating)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='aem',
            field=models.FloatField(blank=True, help_text='Adjusted Net Rating (AOR - ADR)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='aor',
            field=models.FloatField(blank=True, help_text='Adjusted Offensive Rating (pts/100 possessions)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='aor_100',
            field=models.FloatField(blank=True, help_text='AOR mapped to 0-100 scale via z-score', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='net_100',
            field=models.FloatField(blank=True, help_text='Net Rating mapped to 0-100 scale via z-score', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='rank_adr',
            field=models.IntegerField(blank=True, help_text='Rank by ADR (1 = best defense)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='rank_aem',
            field=models.IntegerField(blank=True, help_text='Rank by AEM/Net (1 = best overall)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='rank_aor',
            field=models.IntegerField(blank=True, help_text='Rank by AOR (1 = best offense)', null=True),
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('opponent_name', models.CharField(help_text='Opponent name (for matching)', max_length=100)),
                ('location', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('N', 'Neutral')], help_text='H=Home, A=Away, N=Neutral', max_length=1)),
                ('pts', models.IntegerField(help_text='Points scored')),
                ('pts_allowed', models.IntegerField(help_text='Points allowed')),
                ('fga', models.IntegerField(help_text='Field goal attempts')),
                ('fgm', models.IntegerField(blank=True, help_text='Field goals made', null=True)),
                ('or_total', models.IntegerField(db_column='offensive_rebounds', help_text='Offensive rebounds')),
                ('to', models.IntegerField(help_text='Turnovers')),
                ('fta', models.IntegerField(help_text='Free throw attempts')),
                ('ftm', models.IntegerField(blank=True, help_text='Free throws made', null=True)),
                ('opp_fga', models.IntegerField(blank=True, help_text='Opponent field goal attempts', null=True)),
                ('opp_or', models.IntegerField(blank=True, help_text='Opponent offensive rebounds', null=True)),
                ('opp_to', models.IntegerField(blank=True, help_text='Opponent turnovers', null=True)),
                ('opp_fta', models.IntegerField(blank=True, help_text='Opponent free throw attempts', null=True)),
                ('possessions', models.FloatField(blank=True, help_text='Estimated possessions via formula', null=True)),
                ('raw_oe', models.FloatField(blank=True, help_text='Raw offensive efficiency (pts/100 poss)', null=True)),
                ('raw_de', models.FloatField(blank=True, help_text='Raw defensive efficiency (pts allowed/100 poss)', null=True)),
                ('opp_adj_o', models.FloatField(blank=True, help_text="Opponent's adjusted offensive rating (for defense calc)", null=True)),
                ('opp_adj_d', models.FloatField(blank=True, help_text="Opponent's adjusted defensive rating (for offense calc)", null=True)),
                ('aor_game', models.FloatField(blank=True, help_text="This game's AOR (with venue tax)", null=True)),
                ('adr_game', models.FloatField(blank=True, help_text="This game's ADR (with venue tax)", null=True)),
                ('recency_mult', models.FloatField(default=1.0, help_text='Recency multiplier (future use)')),
                ('weight', models.FloatField(blank=True, help_text='Game weight = possessions * recency_mult', null=True)),
                ('won', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_games', to='core.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_logs', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_logs', to='core.team')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['team', 'season', 'date'], name='core_gamelo_team_id_7522f5_idx'), models.Index(fields=['date'], name='core_gamelo_date_eb05da_idx')],
                'unique_together': {('team', 'date', 'opponent_name')},
            },
        ),
    ]
