# Generated by Django 5.0.1 on 2026-02-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_adjusted_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='efg_margin_z',
            field=models.FloatField(blank=True, help_text='eFG Margin Z-score', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='four_factor_index_100',
            field=models.FloatField(blank=True, db_index=True, help_text='Four Factor Index (0-100 scale)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='four_factor_index_wz',
            field=models.FloatField(blank=True, help_text='Four Factor Weighted Z-score', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='ftr_margin_z',
            field=models.FloatField(blank=True, help_text='FTR Margin Z-score', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='rank_four_factor_index_100',
            field=models.IntegerField(blank=True, help_text='Rank by Four Factor Index (1 = best)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='reb_edge_z',
            field=models.FloatField(blank=True, help_text='Rebounding Edge Z-score', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='tov_edge_z',
            field=models.FloatField(blank=True, help_text='Turnover Edge Z-score', null=True),
        ),
    ]
