# Generated by Django 5.0.1 on 2026-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teamseasonstats_efg_margin_z_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='em_d_rate',
            field=models.FloatField(blank=True, help_text='Evan Miya D-Rate (relative to average)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='em_o_rate',
            field=models.FloatField(blank=True, help_text='Evan Miya O-Rate (relative to average)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='em_rating',
            field=models.FloatField(blank=True, help_text='Evan Miya Relative Rating (O+D)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='has_evan_miya',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='rank_em',
            field=models.IntegerField(blank=True, help_text='Evan Miya Relative Ranking', null=True),
        ),
    ]
