# Generated by Django 5.0.1 on 2026-02-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teamseasonstats_em_d_rate_teamseasonstats_em_o_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='ap_poll_week6',
            field=models.IntegerField(blank=True, help_text='AP Poll ranking at week 6', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='ft_pct',
            field=models.FloatField(blank=True, help_text='Free throw percentage', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='t_rank',
            field=models.IntegerField(blank=True, help_text='T-Rank (Torvik composite ranking)', null=True),
        ),
    ]
