# Generated by Django 5.0.1 on 2026-02-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teamseasonstats_ap_poll_week6_teamseasonstats_ft_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_ast_g',
            field=models.FloatField(blank=True, help_text='Assists per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_ast_pct',
            field=models.FloatField(blank=True, help_text='Assist percentage', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_blk_g',
            field=models.FloatField(blank=True, help_text='Blocks per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_blk_pct',
            field=models.FloatField(blank=True, help_text='Block percentage', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_dpf_g',
            field=models.FloatField(blank=True, help_text='Defensive personal fouls per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_drb_g',
            field=models.FloatField(blank=True, help_text='Defensive rebounds per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_fg_pct',
            field=models.FloatField(blank=True, help_text='Field goal percentage', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_hkm_pct',
            field=models.FloatField(blank=True, help_text='Help-Kill Metric percentage', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_opf_g',
            field=models.FloatField(blank=True, help_text='Offensive personal fouls per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_pace_raw',
            field=models.FloatField(blank=True, help_text='Raw pace (possessions per game)', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_pf_g',
            field=models.FloatField(blank=True, help_text='Personal fouls per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_pts_g',
            field=models.FloatField(blank=True, help_text='Points per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_reb_g',
            field=models.FloatField(blank=True, help_text='Rebounds per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_stl_g',
            field=models.FloatField(blank=True, help_text='Steals per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='cbb_tov_g',
            field=models.FloatField(blank=True, help_text='Turnovers per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='em_kill_shot_margin_pg',
            field=models.FloatField(blank=True, help_text='Kill Shot margin per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='em_kill_shots_conceded_pg',
            field=models.FloatField(blank=True, help_text='Kill Shots conceded per game', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonstats',
            name='em_kill_shots_pg',
            field=models.FloatField(blank=True, help_text='Kill Shots per game', null=True),
        ),
        migrations.AlterField(
            model_name='teamseasonstats',
            name='reb_edge',
            field=models.FloatField(default=0, help_text='ORB% - Opponent ORB%'),
        ),
    ]
