# Generated by Django 5.0.1 on 2026-02-20 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game_log_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_ortg', models.FloatField(help_text='National average offensive rating')),
                ('avg_pace', models.FloatField(help_text='National average pace')),
                ('avg_efg', models.FloatField(help_text='National average eFG%')),
                ('avg_tov', models.FloatField(help_text='National average TOV%')),
                ('avg_orb', models.FloatField(help_text='National average ORB%')),
                ('avg_ftr', models.FloatField(help_text='National average FTR')),
                ('total_possessions', models.FloatField(help_text='Total possessions across all games')),
                ('total_games', models.IntegerField(help_text='Total games in dataset')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='national_averages', to='core.season')),
            ],
            options={
                'verbose_name': 'National Averages',
                'verbose_name_plural': 'National Averages',
            },
        ),
    ]
