# Generated by Django 5.0.1 on 2026-02-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_teamseasonratings_adj_drb_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonmetrics',
            name='opp_orb_pct',
            field=models.FloatField(default=0.0, help_text='Opponent ORB%'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_opp_orb_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Opponent ORB%'),
        ),
    ]
