# Generated by Django 5.0.1 on 2026-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_teamseasonmetrics_opp_orb_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_d1',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this a Division I team? False for non-D1 opponents.'),
        ),
    ]
