# Generated by Django 5.0.1 on 2026-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_matchup_prediction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaverages',
            name='coef_efg',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Regression coefficient for eFG% edge (points per % edge)'
            ),
        ),
        migrations.AddField(
            model_name='nationalaverages',
            name='coef_tov',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Regression coefficient for TOV% edge (points per % edge)'
            ),
        ),
        migrations.AddField(
            model_name='nationalaverages',
            name='coef_orb',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Regression coefficient for ORB% edge (points per % edge)'
            ),
        ),
        migrations.AddField(
            model_name='nationalaverages',
            name='coef_ftr',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Regression coefficient for FTR edge (points per % edge)'
            ),
        ),
        migrations.AddField(
            model_name='nationalaverages',
            name='coef_intercept',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Regression intercept (baseline margin)'
            ),
        ),
        migrations.AddField(
            model_name='nationalaverages',
            name='coef_r_squared',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='R-squared of four factor regression model'
            ),
        ),
    ]
