# Generated by Django 6.0.2 on 2026-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_four_factor_coefficients'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonratings',
            name='wab',
            field=models.FloatField(blank=True, help_text='Wins Above Bubble', null=True),
        ),
    ]
