# Generated by Django 6.0.2 on 2026-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_teamseasonratings_wab'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonratings',
            name='net_rank',
            field=models.IntegerField(blank=True, help_text='NCAA NET ranking', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='sor_rank',
            field=models.IntegerField(blank=True, help_text='Strength of Record rank', null=True),
        ),
    ]
