# Generated by Django 5.0.1 on 2026-03-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dataprocessingjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dataprocessingjob',
            new_name='core_datapr_job_id_68473b_idx',
            old_name='core_datapr_job_id_idx',
        ),
        migrations.RenameIndex(
            model_name='dataprocessingjob',
            new_name='core_datapr_status_ca8644_idx',
            old_name='core_datapr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='dataprocessingjob',
            new_name='core_datapr_season__e72de2_idx',
            old_name='core_datapr_season_idx',
        ),
        migrations.AlterField(
            model_name='dataprocessingjob',
            name='job_type',
            field=models.CharField(choices=[('update_all', 'Full Data Update'), ('ingest_gamelogs', 'Ingest Game Logs'), ('compute_team_metrics', 'Compute Team Metrics'), ('compute_adjusted_ratings', 'Compute Adjusted Ratings'), ('compute_four_factor_index', 'Compute Four Factor Index'), ('fetch_net_rankings', 'Fetch NCAA NET Rankings'), ('compute_sor', 'Compute Strength of Record'), ('compute_game_value', 'Compute Game Value'), ('compute_sos', 'Compute Strength of Schedule')], help_text='Type of data processing job', max_length=30),
        ),
    ]
