# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_load_ncaa_name_mappings"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamseasonmetrics",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                help_text="Conference for this team-season (for filtering/display)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_metrics",
                to="core.conference",
            ),
        ),
    ]
