# Generated by Django 5.0.1 on 2026-04-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tournament_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_athlete_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('jersey', models.CharField(blank=True, default='', max_length=5)),
                ('position', models.CharField(blank=True, default='', help_text='Position abbreviation (G, F, C)', max_length=10)),
                ('headshot_url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='dataprocessingjob',
            name='job_id',
            field=models.CharField(help_text='Unique job identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='adj_ratings_iterations',
            field=models.IntegerField(default=75, help_text='Max solver iterations before declaring convergence (compute_adjusted_ratings --iterations)'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='ffi_weight_efg',
            field=models.FloatField(default=0.47, help_text='eFG% margin weight in the FFI composite score'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='ffi_weight_ftr',
            field=models.FloatField(default=0.08, help_text='FTR margin weight in the FFI composite score'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='ffi_weight_reb',
            field=models.FloatField(default=0.21, help_text='Rebounding edge weight in the FFI composite score'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='ffi_weight_tov',
            field=models.FloatField(default=0.24, help_text='Turnover edge weight in the FFI composite score'),
        ),
        migrations.AlterField(
            model_name='pipelineconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.IntegerField(default=0, help_text='Games played')),
                ('mpg', models.FloatField(default=0.0, help_text='Minutes per game')),
                ('pts', models.FloatField(default=0.0)),
                ('reb', models.FloatField(default=0.0)),
                ('ast', models.FloatField(default=0.0)),
                ('stl', models.FloatField(default=0.0)),
                ('blk', models.FloatField(default=0.0)),
                ('tov', models.FloatField(default=0.0)),
                ('pf', models.FloatField(default=0.0)),
                ('fg_pct', models.FloatField(blank=True, null=True)),
                ('fg3_pct', models.FloatField(blank=True, null=True)),
                ('ft_pct', models.FloatField(blank=True, null=True)),
                ('fga_pg', models.FloatField(default=0.0, help_text='FG attempts per game')),
                ('fg3a_pg', models.FloatField(default=0.0, help_text='3PA per game')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='core.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_stats', to='core.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_season_stats', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=False)),
                ('did_not_play', models.BooleanField(default=False)),
                ('minutes', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=0)),
                ('fg_made', models.IntegerField(default=0)),
                ('fg_attempted', models.IntegerField(default=0)),
                ('fg3_made', models.IntegerField(default=0)),
                ('fg3_attempted', models.IntegerField(default=0)),
                ('ft_made', models.IntegerField(default=0)),
                ('ft_attempted', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('offensive_rebounds', models.IntegerField(default=0)),
                ('defensive_rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='core.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_game_stats', to='core.team')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='core_player_game_id_e7a76e_idx'), models.Index(fields=['player', 'team'], name='core_player_player__a090a3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playergamestats',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='unique_player_game'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['team', 'season'], name='core_player_team_id_6e7d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['player', 'season'], name='core_player_player__f7705d_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerseasonstats',
            constraint=models.UniqueConstraint(fields=('player', 'season', 'team'), name='unique_player_season_team'),
        ),
    ]
