# Generated by Django 5.0.1 on 2026-04-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_player_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_def_pg',
            field=models.FloatField(blank=True, help_text='Avg team pts allowed while on per game', null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_drtg',
            field=models.FloatField(blank=True, help_text='On-court opp pts per 40 min on court (raw, from PBP)', null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_net',
            field=models.FloatField(blank=True, help_text='On-court net rating per 40 min on court (raw, from PBP)', null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_net_pg',
            field=models.FloatField(blank=True, help_text='Avg net pts while on per game', null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_ortg',
            field=models.FloatField(blank=True, help_text='On-court pts per 40 min on court (raw, from PBP)', null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_pts_pg',
            field=models.FloatField(blank=True, help_text='Avg team pts scored while on per game', null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstats',
            name='on_court_secs_pg',
            field=models.FloatField(blank=True, help_text='Avg seconds on court per game (from PBP)', null=True),
        ),
        migrations.CreateModel(
            name='PlayerGameStint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stint_index', models.IntegerField(help_text='0-based sequential per (player, game)')),
                ('period', models.IntegerField(default=1, help_text='1=first half, 2=second half, 3+=OT')),
                ('clock_start_secs', models.IntegerField(help_text='Seconds remaining in period at stint start')),
                ('clock_end_secs', models.IntegerField(help_text='Seconds remaining in period at stint end')),
                ('secs_on', models.IntegerField(default=0, help_text='Duration in seconds (clock_start - clock_end)')),
                ('pts_scored', models.IntegerField(default=0, help_text='Team pts scored while this player was on court')),
                ('pts_allowed', models.IntegerField(default=0, help_text='Opp pts scored while this player was on court')),
                ('plus_minus', models.IntegerField(default=0, help_text='pts_scored - pts_allowed')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stints', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stints', to='core.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_stints', to='core.team')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'team'], name='core_player_game_id_11fec9_idx'), models.Index(fields=['player', 'game'], name='core_player_player__207edd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playergamestint',
            constraint=models.UniqueConstraint(fields=('player', 'game', 'stint_index'), name='unique_player_game_stint'),
        ),
    ]
