# Generated by Django 5.0.1 on 2026-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_team_roster_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrosterfit',
            name='adjusted_def_fit',
            field=models.FloatField(blank=True, help_text='Phase 3 defensive_fit_score + def_contextual_modifier', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='adjusted_off_fit',
            field=models.FloatField(blank=True, help_text='Phase 3 offensive_fit_score + off_contextual_modifier', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='adjusted_overall_fit',
            field=models.FloatField(blank=True, help_text='Recomputed overall from adjusted off/def fits', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='def_contextual_modifier',
            field=models.FloatField(blank=True, help_text='pace(50%) + def_scheme modifier, clamped ±5', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='def_scheme_alignment_score',
            field=models.FloatField(blank=True, help_text='0-100: how well roster archetypes match team defensive scheme', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='def_scheme_modifier',
            field=models.FloatField(blank=True, help_text='Defensive scheme modifier (-3 to +3)', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='has_team_style_data',
            field=models.BooleanField(default=False, help_text='True if TeamSeasonRatings data existed for this team; False means all Phase 4 fields are neutral placeholders'),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='off_contextual_modifier',
            field=models.FloatField(blank=True, help_text='pace(100%) + off_scheme modifier, clamped ±5', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='off_scheme_alignment_score',
            field=models.FloatField(blank=True, help_text='0-100: how well roster archetypes match team offensive scheme', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='off_scheme_modifier',
            field=models.FloatField(blank=True, help_text='Offensive scheme modifier (-3 to +3)', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='pace_alignment_score',
            field=models.FloatField(blank=True, help_text='0-100: how well roster pace tendency matches team tempo identity', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='pace_modifier',
            field=models.FloatField(blank=True, help_text='Pace modifier (-2 to +2); applied 100% to off, 50% to def', null=True),
        ),
    ]
