# Generated by Django 5.0.1 on 2026-04-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_team_season_projection'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonprojection',
            name='continuity_value_score',
            field=models.FloatField(blank=True, help_text='Phase 6: BPR-weighted continuity index, 0-100. Blend of returner_minutes_fraction (60%) and returner_bpr_fraction (40%). Drives continuity_adjustment_off/def — stable teams that keep their key contributors execute systems more reliably.', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonprojection',
            name='returner_bpr_fraction',
            field=models.FloatField(blank=True, help_text='Phase 6: fraction (0-1) of BPR-weighted output from returners. Higher than returner_minutes_fraction means returners are above-average contributors.', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonprojection',
            name='transfer_bpr_fraction',
            field=models.FloatField(blank=True, help_text='Phase 6: fraction (0-1) of BPR-weighted output from transfers', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonprojection',
            name='transfer_dependence_score',
            field=models.FloatField(blank=True, help_text='Phase 6: transfer_bpr_fraction × 100; 0-100. High score = team performance heavily reliant on transfers.', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonprojection',
            name='transfer_minutes_fraction',
            field=models.FloatField(blank=True, help_text='Phase 6: fraction (0-1) of projected minutes allocated to transfers', null=True),
        ),
    ]
