# Generated by Django 5.0.1 on 2026-04-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_phase6_stability_diagnostics'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonprojection',
            name='transfer_fit_risk_score',
            field=models.FloatField(blank=True, help_text='Phase 6b: transfer fit-risk ∈ [0, 1]. Interaction of transfer_dependence_score × fit_shortfall (below-neutral fit). Feeds into team_projection_uncertainty; does not affect mean ratings.', null=True),
        ),
    ]
