# Generated by Django 5.0.1 on 2026-04-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_phase6b_transfer_fit_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Stable slug, e.g. 'power_starter_g'", max_length=64, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable label shown in UI', max_length=128)),
                ('conf_group', models.CharField(choices=[('national', 'National (All D1)'), ('power', 'Power Conference'), ('mid_major', 'Mid-Major')], db_index=True, max_length=16)),
                ('role_bucket', models.CharField(choices=[('G', 'Guard'), ('Wing', 'Wing'), ('Big', 'Big')], db_index=True, max_length=8)),
                ('quality_tier', models.CharField(choices=[('elite', 'Elite (All-American)'), ('starter', 'Starter'), ('rotation', 'Rotation')], db_index=True, max_length=16)),
                ('projected_obpr', models.FloatField()),
                ('projected_dbpr', models.FloatField()),
                ('projected_bpr', models.FloatField()),
                ('minutes_share', models.FloatField(help_text='Median minutes_share_p2 of bucket')),
                ('mpg', models.FloatField(help_text='Median mpg_p2 of bucket')),
                ('uncertainty', models.FloatField(help_text='Median projection_uncertainty of bucket')),
                ('efg_pct', models.FloatField(blank=True, null=True)),
                ('fg3_pct', models.FloatField(blank=True, null=True)),
                ('ts_pct', models.FloatField(blank=True, null=True)),
                ('ast_to', models.FloatField(blank=True, null=True)),
                ('oreb_pg', models.FloatField(blank=True, null=True)),
                ('dreb_pg', models.FloatField(blank=True, null=True)),
                ('tov', models.FloatField(blank=True, help_text='Median turnovers per game', null=True)),
                ('sample_n', models.IntegerField(help_text='Number of real players in source bucket')),
                ('source_season_year', models.IntegerField(help_text='Season year (from_season.year) data was drawn from')),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['conf_group', 'role_bucket', 'quality_tier'],
                'indexes': [models.Index(fields=['conf_group', 'role_bucket', 'quality_tier'], name='core_placeh_conf_gr_e749f7_idx')],
            },
        ),
    ]
