# Generated by Django 5.0.1 on 2026-04-24 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_placeholder_archetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholderarchetype',
            name='conf_group',
            field=models.CharField(choices=[('national', 'National (All D1)'), ('power', 'Power Conference'), ('high_mid', 'High Mid-Major (WCC, MWC, A10, Amer)'), ('mid_major', 'Mid-Major')], db_index=True, max_length=16),
        ),
        migrations.CreateModel(
            name='PlayerRecruitingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.IntegerField(db_index=True, help_text="Season year of the player's first college season (matches Season.year).")),
                ('stars', models.IntegerField(blank=True, choices=[(1, '1-star'), (2, '2-star'), (3, '3-star'), (4, '4-star'), (5, '5-star')], help_text='Star rating (1–5). Null for unrated / walk-on prospects.', null=True)),
                ('national_rank', models.IntegerField(blank=True, help_text='Overall national recruiting rank (1-based). Lower is better.', null=True)),
                ('composite_score', models.FloatField(blank=True, help_text='247Sports-style composite score in [0, 1].  ~1.000 = top recruit; ~0.980+ = 5-star; ~0.950-0.979 = 4-star; ~0.880-0.949 = 3-star; <0.880 = 2-star or below.', null=True)),
                ('position_rank', models.IntegerField(blank=True, help_text="Rank within the player's position group.", null=True)),
                ('source', models.CharField(choices=[('247sports', '247Sports'), ('rivals', 'Rivals'), ('espn', 'ESPN'), ('on3', 'On3'), ('manual', 'Manual entry')], default='manual', help_text='Where the recruiting data originated.', max_length=30)),
                ('notes', models.CharField(blank=True, default='', help_text="Free-text notes (e.g. 'consensus 5-star; top-5 national').", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_profiles', to='core.player')),
            ],
            options={
                'ordering': ['class_year', 'national_rank'],
                'indexes': [models.Index(fields=['class_year'], name='core_player_class_y_4827ab_idx'), models.Index(fields=['stars', 'class_year'], name='core_player_stars_e13ddb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playerrecruitingprofile',
            constraint=models.UniqueConstraint(fields=('player', 'class_year'), name='unique_player_class_year'),
        ),
    ]
