# Generated by Django 5.0.1 on 2026-04-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncaa', '0048_player_recruiting_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholderarchetype',
            name='quality_tier',
            field=models.CharField(choices=[('elite', 'Elite (All-American)'), ('all_conference', 'All-Conference'), ('starter', 'Starter'), ('rotation', 'Rotation'), ('bench', 'Bench')], db_index=True, max_length=16),
        ),
    ]
