# Generated by Django 5.0.1 on 2026-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_placeholder_archetype_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprocessingjob',
            name='job_type',
            field=models.CharField(choices=[('update_all', 'Full Data Update'), ('update_ncaa_teams', 'NCAA Update Teams'), ('update_ncaa_players', 'NCAA Update Players'), ('update_nba_teams', 'NBA Update Teams'), ('update_nba_players', 'NBA Update Players'), ('ingest_gamelogs', 'Ingest Game Logs'), ('compute_team_metrics', 'Compute Team Metrics'), ('compute_adjusted_ratings', 'Compute Adjusted Ratings'), ('compute_four_factor_index', 'Compute Four Factor Index'), ('fetch_net_rankings', 'Fetch NCAA NET Rankings'), ('compute_sor', 'Compute Strength of Record'), ('compute_game_value', 'Compute Game Value'), ('compute_sos', 'Compute Strength of Schedule')], help_text='Type of data processing job', max_length=30),
        ),
    ]
