# Generated by Django 5.0.1 on 2026-05-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_placeholder_conference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scenariosnapshot',
            new_name='core_scenar_team_id_8181dc_idx',
            old_name='core_scenar_team_id_from_sea_idx',
        ),
    ]
