# Generated by Django 5.0.1 on 2026-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_game_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonratings',
            name='tournament_finish',
            field=models.CharField(blank=True, choices=[('Champ', 'Champion'), ('Runner-Up', 'Runner-Up'), ('Final Four', 'Final Four'), ('Elite Eight', 'Elite Eight'), ('Sweet 16', 'Sweet 16'), ('Round of 32', 'Round of 32'), ('Round of 64', 'Round of 64'), ('First Four', 'First Four')], help_text='NCAA Tournament finish', max_length=20, null=True),
        ),
    ]
