# Generated by Django 5.0.1 on 2026-06-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_teamseasonratings_tournament_finish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamseasonmetrics',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonratings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='selection_sunday_date',
            field=models.DateField(blank=True, help_text='Date of Selection Sunday for this season', null=True),
        ),
        migrations.AddField(
            model_name='teamseasonmetrics',
            name='is_pre_tournament',
            field=models.BooleanField(default=False, help_text='True if this metric was computed using only pre-tournament games (on or before Selection Sunday)'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='is_pre_tournament',
            field=models.BooleanField(default=False, help_text='True if this rating was computed using only pre-tournament games (on or before Selection Sunday)'),
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonmetrics',
            unique_together={('team', 'season', 'is_pre_tournament')},
        ),
        migrations.AlterUniqueTogether(
            name='teamseasonratings',
            unique_together={('team', 'season', 'is_pre_tournament')},
        ),
    ]
