# Generated by Django 5.0.1 on 2026-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_teamseasonmetrics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Game arena elevation in feet', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Home arena elevation in feet', null=True),
        ),
    ]
