# Generated by Django 5.0.1 on 2026-06-11 17:05

from django.db import migrations, models


def bump_ff_iterations(apps, schema_editor):
    # Existing rows keep their old field value (3) on AlterField; bump to the new
    # default (75) now that compute_adjusted_four_factors uses shrinkage +
    # convergence instead of a fixed iteration count.
    PipelineConfig = apps.get_model("core", "PipelineConfig")
    PipelineConfig.objects.filter(pk=1, adj_ff_iterations=3).update(adj_ff_iterations=75)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_playeravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineconfig",
            name="adj_ff_convergence",
            field=models.FloatField(
                default=0.01,
                help_text="Max change (percentage points) in any adjusted four factor stat between iterations to declare convergence",
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfig",
            name="adj_ff_shrinkage_ceiling",
            field=models.IntegerField(
                default=300, help_text="Starting/maximum shrinkage constant (possessions)"
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfig",
            name="adj_ff_shrinkage_decay",
            field=models.FloatField(
                default=6.25, help_text="Shrinkage k drops by this amount per average game played"
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfig",
            name="adj_ff_shrinkage_floor",
            field=models.IntegerField(
                default=150,
                help_text="Minimum shrinkage constant (possessions) regardless of games played",
            ),
        ),
        migrations.AlterField(
            model_name="pipelineconfig",
            name="adj_ff_iterations",
            field=models.IntegerField(
                default=75,
                help_text="Max solver iterations before declaring convergence (compute_adjusted_four_factors --iterations)",
            ),
        ),
        migrations.RunPython(bump_ff_iterations, migrations.RunPython.noop),
    ]
