# Generated by Django 5.0.1 on 2026-06-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_pipelineconfig_adj_ff_convergence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineconfig",
            name="importance_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable Lorentzian importance weighting in adj ratings solver",
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfig",
            name="recency_lambda",
            field=models.FloatField(
                default=0.004,
                help_text="Exponential decay λ for recency weighting in adj ratings solver (0 = disabled)",
            ),
        ),
    ]
