# Generated by Django 5.0.1 on 2026-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_add_recency_lambda_importance_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineconfig",
            name="bpr_prior_decay_games",
            field=models.IntegerField(
                default=30, help_text="Games per team over which BPR prior fades to league average"
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfig",
            name="bpr_prior_min_coverage",
            field=models.FloatField(
                default=0.95,
                help_text="Minimum fraction of D1 teams with projections required to enable BPR prior",
            ),
        ),
        migrations.AddField(
            model_name="pipelineconfig",
            name="use_bpr_prior",
            field=models.BooleanField(
                default=False,
                help_text="Anchor early-season shrinkage to BPR projections (auto-disabled if coverage < 95%)",
            ),
        ),
    ]
