# Generated by Django 5.0.1 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_add_bpr_prior_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasonstats",
            name="usg_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Usage% = (FGA + 0.44*FTA + TOV) / team_poss * (tm_mp/5/mp) * 100",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="tov_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Turnover% = TOV / (FGA + 0.44*FTA + TOV) * 100",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="orb_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Offensive Rebound% (minutes-adjusted)",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="drb_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Defensive Rebound% (minutes-adjusted)",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="fta_rate",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="FTA Rate = FTA / FGA",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="fg3_rate",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="3PA Rate = FG3A / FGA",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="blk_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Block% vs opp 2PA (minutes-adjusted)",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="stl_pct",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="Steal% vs opp possessions (minutes-adjusted)",
            ),
        ),
        migrations.AddField(
            model_name="playerseasonstats",
            name="ast_usg",
            field=models.FloatField(
                blank=True,
                null=True,
                help_text="AST/USG = assists per game / usg_pct",
            ),
        ),
    ]
