# Generated by Django 5.0.1 on 2026-07-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_add_player_rate_stats'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerrecruitingprofile',
            name='unique_player_class_year',
        ),
        migrations.AddField(
            model_name='playerrecruitingprofile',
            name='committed_team',
            field=models.ForeignKey(blank=True, help_text='Team the recruit has committed to (null = uncommitted/unknown).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruit_commits', to='core.team'),
        ),
        migrations.AddField(
            model_name='playerrecruitingprofile',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Diacritic/suffix-normalized recruit_name for matching.', max_length=150),
        ),
        migrations.AddField(
            model_name='playerrecruitingprofile',
            name='recruit_name',
            field=models.CharField(blank=True, default='', help_text="Recruit's name as listed by the source (for unresolved profiles).", max_length=150),
        ),
        migrations.AddField(
            model_name='playerrecruitingprofile',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='URL of the source page/export this profile came from.', max_length=300),
        ),
        migrations.AlterField(
            model_name='playerrecruitingprofile',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiting_profiles', to='core.player'),
        ),
        migrations.AddConstraint(
            model_name='playerrecruitingprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('player', 'class_year'), name='unique_player_class_year'),
        ),
        migrations.AddConstraint(
            model_name='playerrecruitingprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', True)), fields=('normalized_name', 'class_year', 'source'), name='unique_unresolved_recruit'),
        ),
    ]
