# Generated by Django 5.0.1 on 2026-07-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_playerrecruitingprofile_unique_player_class_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMarketValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpr', models.FloatField(help_text='Actual season BPR (obpr + dbpr)')),
                ('minutes_share', models.FloatField(help_text='mpg / 40 (5.0-pool convention)')),
                ('marginal_em', models.FloatField(help_text='EM above replacement contributed')),
                ('marginal_wins', models.FloatField(help_text='marginal_em × WINS_PER_EM_NCAA')),
                ('value_low', models.FloatField(help_text='Dollars, low anchor (17% MBB share)')),
                ('value_high', models.FloatField(help_text='Dollars, high anchor (23% MBB share)')),
                ('pipeline_version', models.CharField(blank=True, default='', max_length=20)),
                ('constants_hash', models.CharField(blank=True, default='', help_text='Hash of the constant set that produced this row (provenance)', max_length=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_values', to='core.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_market_values', to='core.season')),
            ],
            options={
                'ordering': ['-marginal_wins'],
                'indexes': [models.Index(fields=['season', '-marginal_wins'], name='core_player_season__184575_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playermarketvalue',
            constraint=models.UniqueConstraint(fields=('player', 'season'), name='unique_player_market_value'),
        ),
    ]
