"""
Update team logo URLs in the database using proper manual mapping

This script uses the KenPom to ESPN mapping and matches to actual logo files
"""
import os
import sys
import django
from pathlib import Path

# Setup Django
sys.path.insert(0, r'C:\Users\spenc\OneDrive\Workspace\CBB Analytical Dashboard\backend')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from core.models import Team

# Path to logos
LOGOS_DIR = Path(r'C:\Users\spenc\OneDrive\Workspace\CBB Analytical Dashboard\frontend\public\logos')

# Get all logo files - map stem to filename
logo_files = {f.stem: f.name for f in LOGOS_DIR.glob('*.png')}

print(f"Found {len(logo_files)} logo files\n")

# Manual mapping of team names to logo file stems (without .png extension)
# Based on the actual filenames in our logos directory
TEAM_TO_LOGO_STEM = {
    "Abilene Christian": "abilene_christian_wildcats",
    "Air Force": "air_force_falcons",
    "Akron": "akron_zips",
    "Alabama": "alabama_crimson_tide",
    "Alabama A&M": "alabama_am_bulldogs",
    "Alabama St.": "alabama_state_hornets",
    "Albany": "ualbany_great_danes",
    "Alcorn St.": "alcorn_state_braves",
    "American": "american_university_eagles",
    "Appalachian St.": "app_state_mountaineers",
    "Arizona": "arizona_wildcats",
    "Arizona St.": "arizona_state_sun_devils",
    "Arkansas": "arkansas_razorbacks",
    "Arkansas Pine Bluff": "arkansas-pine_bluff_golden_lions",
    "Arkansas St.": "arkansas_state_red_wolves",
    "Army": "army_black_knights",
    "Auburn": "auburn_tigers",
    "Austin Peay": "austin_peay_governors",
    "BYU": "byu_cougars",
    "Ball St.": "ball_state_cardinals",
    "Baylor": "baylor_bears",
    "Bellarmine": "bellarmine_knights",
    "Belmont": "belmont_bruins",
    "Bethune Cookman": "bethune-cookman_wildcats",
    "Binghamton": "binghamton_bearcats",
    "Boise St.": "boise_state_broncos",
    "Boston College": "boston_college_eagles",
    "Boston University": "boston_university_terriers",
    "Bowling Green": "bowling_green_falcons",
    "Bradley": "bradley_braves",
    "Brown": "brown_bears",
    "Bryant": "bryant_bulldogs",
    "Bucknell": "bucknell_bison",
    "Buffalo": "buffalo_bulls",
    "Butler": "butler_bulldogs",
    "CSUN": "cal_state_northridge_matadors",
    "Cal St. Northridge": "cal_state_northridge_matadors",
    "Cal Baptist": "california_baptist_lancers",
    "Cal Poly": "cal_poly_mustangs",
    "Cal St. Bakersfield": "cal_state_bakersfield_roadrunners",
    "Cal St. Fullerton": "cal_state_fullerton_titans",
    "California": "california_golden_bears",
    "Campbell": "campbell_fighting_camels",
    "Canisius": "canisius_golden_griffins",
    "Central Arkansas": "central_arkansas_bears",
    "Central Connecticut": "central_connecticut_blue_devils",
    "Central Michigan": "central_michigan_chippewas",
    "Charleston": "charleston_cougars",
    "Charleston Southern": "charleston_southern_buccaneers",
    "Charlotte": "charlotte_49ers",
    "Chattanooga": "chattanooga_mocs",
    "Chicago St.": "chicago_state_cougars",
    "Cincinnati": "cincinnati_bearcats",
    "Clemson": "clemson_tigers",
    "Cleveland St.": "cleveland_state_vikings",
    "Coastal Carolina": "coastal_carolina_chanticleers",
    "Colgate": "colgate_raiders",
    "Colorado": "colorado_buffaloes",
    "Colorado St.": "colorado_state_rams",
    "Columbia": "columbia_lions",
    "Connecticut": "uconn_huskies",
    "Coppin St.": "coppin_state_eagles",
    "Cornell": "cornell_big_red",
    "Creighton": "creighton_bluejays",
    "Dartmouth": "dartmouth_big_green",
    "Davidson": "davidson_wildcats",
    "Dayton": "dayton_flyers",
    "DePaul": "depaul_blue_demons",
    "Delaware": "delaware_blue_hens",
    "Delaware St.": "delaware_state_hornets",
    "Denver": "denver_pioneers",
    "Detroit Mercy": "detroit_mercy_titans",
    "Drake": "drake_bulldogs",
    "Drexel": "drexel_dragons",
    "Duke": "duke_blue_devils",
    "Duquesne": "duquesne_dukes",
    "East Carolina": "east_carolina_pirates",
    "East Tennessee St.": "east_tennessee_state_buccaneers",
    "East Texas A&M": "east_texas_am_lions",
    "Eastern Illinois": "eastern_illinois_panthers",
    "Eastern Kentucky": "eastern_kentucky_colonels",
    "Eastern Michigan": "eastern_michigan_eagles",
    "Eastern Washington": "eastern_washington_eagles",
    "Elon": "elon_phoenix",
    "Evansville": "evansville_purple_aces",
    "FIU": "florida_international_panthers",
    "Fairfield": "fairfield_stags",
    "Fairleigh Dickinson": "fairleigh_dickinson_knights",
    "Florida": "florida_gators",
    "Florida A&M": "florida_am_rattlers",
    "Florida Atlantic": "florida_atlantic_owls",
    "Florida Gulf Coast": "florida_gulf_coast_eagles",
    "Florida St.": "florida_state_seminoles",
    "Fordham": "fordham_rams",
    "Fresno St.": "fresno_state_bulldogs",
    "Furman": "furman_paladins",
    "Gardner Webb": "gardner-webb_runnin_bulldogs",
    "George Mason": "george_mason_patriots",
    "George Washington": "george_washington_revolutionaries",
    "Georgetown": "georgetown_hoyas",
    "Georgia": "georgia_bulldogs",
    "Georgia Southern": "georgia_southern_eagles",
    "Georgia St.": "georgia_state_panthers",
    "Georgia Tech": "georgia_tech_yellow_jackets",
    "Gonzaga": "gonzaga_bulldogs",
    "Grambling St.": "grambling_tigers",
    "Grand Canyon": "grand_canyon_lopes",
    "Green Bay": "green_bay_phoenix",
    "Hampton": "hampton_pirates",
    "Harvard": "harvard_crimson",
    "Hawaii": "hawaii_rainbow_warriors",
    "High Point": "high_point_panthers",
    "Hofstra": "hofstra_pride",
    "Holy Cross": "holy_cross_crusaders",
    "Houston": "houston_cougars",
    "Houston Christian": "houston_christian_huskies",
    "Howard": "howard_bison",
    "IU Indy": "iu_indianapolis_jaguars",
    "Idaho": "idaho_vandals",
    "Idaho St.": "idaho_state_bengals",
    "Illinois": "illinois_fighting_illini",
    "Illinois Chicago": "uic_flames",
    "Illinois St.": "illinois_state_redbirds",
    "Incarnate Word": "incarnate_word_cardinals",
    "Indiana": "indiana_hoosiers",
    "Indiana St.": "indiana_state_sycamores",
    "Iona": "iona_gaels",
    "Iowa": "iowa_hawkeyes",
    "Iowa St.": "iowa_state_cyclones",
    "Jackson St.": "jackson_state_tigers",
    "Jacksonville": "jacksonville_dolphins",
    "Jacksonville St.": "jacksonville_state_gamecocks",
    "James Madison": "james_madison_dukes",
    "Kansas": "kansas_jayhawks",
    "Kansas City": "kansas_city_roos",
    "Kansas St.": "kansas_state_wildcats",
    "Kennesaw St.": "kennesaw_state_owls",
    "Kent St.": "kent_state_golden_flashes",
    "Kentucky": "kentucky_wildcats",
    "LIU": "long_island_university_sharks",
    "LSU": "lsu_tigers",
    "La Salle": "la_salle_explorers",
    "Lafayette": "lafayette_leopards",
    "Lamar": "lamar_cardinals",
    "Le Moyne": "le_moyne_dolphins",
    "Lehigh": "lehigh_mountain_hawks",
    "Liberty": "liberty_flames",
    "Lindenwood": "lindenwood_lions",
    "Lipscomb": "lipscomb_bisons",
    "Little Rock": "little_rock_trojans",
    "Long Beach St.": "long_beach_state_beach",
    "Longwood": "longwood_lancers",
    "Louisiana": "louisiana_ragin_cajuns",
    "Louisiana Monroe": "ul_monroe_warhawks",
    "Louisiana Tech": "louisiana_tech_bulldogs",
    "Louisville": "louisville_cardinals",
    "Loyola Chicago": "loyola_chicago_ramblers",
    "Loyola MD": "loyola_maryland_greyhounds",
    "Loyola Marymount": "loyola_marymount_lions",
    "Maine": "maine_black_bears",
    "Manhattan": "manhattan_jaspers",
    "Marist": "marist_red_foxes",
    "Marquette": "marquette_golden_eagles",
    "Marshall": "marshall_thundering_herd",
    "Maryland": "maryland_terrapins",
    "Maryland Eastern Shore": "maryland_eastern_shore_hawks",
    "Massachusetts": "massachusetts_minutemen",
    "McNeese": "mcneese_cowboys",
    "Memphis": "memphis_tigers",
    "Mercer": "mercer_bears",
    "Mercyhurst": "mercyhurst_lakers",
    "Merrimack": "merrimack_warriors",
    "Miami FL": "miami_hurricanes",
    "Miami (FL)": "miami_hurricanes",
    "Miami OH": "miami_oh_redhawks",
    "Miami (OH)": "miami_oh_redhawks",
    "Michigan": "michigan_wolverines",
    "Michigan St.": "michigan_state_spartans",
    "Michigan State": "michigan_state_spartans",
    "Middle Tennessee": "middle_tennessee_blue_raiders",
    "Milwaukee": "milwaukee_panthers",
    "Minnesota": "minnesota_golden_gophers",
    "Mississippi": "ole_miss_rebels",
    "Mississippi St.": "mississippi_state_bulldogs",
    "Mississippi Valley St.": "mississippi_valley_state_delta_devils",
    "Missouri": "missouri_tigers",
    "Missouri St.": "missouri_state_bears",
    "Monmouth": "monmouth_hawks",
    "Montana": "montana_grizzlies",
    "Montana St.": "montana_state_bobcats",
    "Morehead St.": "morehead_state_eagles",
    "Morgan St.": "morgan_state_bears",
    "Mount St. Mary's": "mount_st_marys_mountaineers",
    "Murray St.": "murray_state_racers",
    "N.C. State": "nc_state_wolfpack",
    "NC State": "nc_state_wolfpack",
    "NJIT": "njit_highlanders",
    "Navy": "navy_midshipmen",
    "Nebraska": "nebraska_cornhuskers",
    "Nebraska Omaha": "omaha_mavericks",
    "Nevada": "nevada_wolf_pack",
    "New Hampshire": "new_hampshire_wildcats",
    "New Haven": "new_haven_chargers",
    "New Mexico": "new_mexico_lobos",
    "New Mexico St.": "new_mexico_state_aggies",
    "New Orleans": "new_orleans_privateers",
    "Niagara": "niagara_purple_eagles",
    "Nicholls": "nicholls_colonels",
    "Nicholls St.": "nicholls_colonels",
    "Norfolk St.": "norfolk_state_spartans",
    "North Alabama": "north_alabama_lions",
    "North Carolina": "north_carolina_tar_heels",
    "North Carolina A&T": "north_carolina_at_aggies",
    "North Carolina Central": "north_carolina_central_eagles",
    "North Dakota": "north_dakota_fighting_hawks",
    "North Dakota St.": "north_dakota_state_bison",
    "North Florida": "north_florida_ospreys",
    "North Texas": "north_texas_mean_green",
    "Northeastern": "northeastern_huskies",
    "Northern Arizona": "northern_arizona_lumberjacks",
    "Northern Colorado": "northern_colorado_bears",
    "Northern Illinois": "northern_illinois_huskies",
    "Northern Iowa": "northern_iowa_panthers",
    "Northern Kentucky": "northern_kentucky_norse",
    "Northwestern": "northwestern_wildcats",
    "Northwestern St.": "northwestern_state_demons",
    "Notre Dame": "notre_dame_fighting_irish",
    "Oakland": "oakland_golden_grizzlies",
    "Ohio": "ohio_bobcats",
    "Ohio St.": "ohio_state_buckeyes",
    "Oklahoma": "oklahoma_sooners",
    "Oklahoma St.": "oklahoma_state_cowboys",
    "Old Dominion": "old_dominion_monarchs",
    "Oral Roberts": "oral_roberts_golden_eagles",
    "Oregon": "oregon_ducks",
    "Oregon St.": "oregon_state_beavers",
    "Pacific": "pacific_tigers",
    "Penn": "pennsylvania_quakers",
    "Penn St.": "penn_state_nittany_lions",
    "Pepperdine": "pepperdine_waves",
    "Pittsburgh": "pittsburgh_panthers",
    "Portland": "portland_pilots",
    "Portland St.": "portland_state_vikings",
    "Prairie View A&M": "prairie_view_am_panthers",
    "Presbyterian": "presbyterian_blue_hose",
    "Princeton": "princeton_tigers",
    "Providence": "providence_friars",
    "Purdue": "purdue_boilermakers",
    "Purdue Fort Wayne": "purdue_fort_wayne_mastodons",
    "Queens": "queens_university_royals",
    "Quinnipiac": "quinnipiac_bobcats",
    "Radford": "radford_highlanders",
    "Rhode Island": "rhode_island_rams",
    "Rice": "rice_owls",
    "Richmond": "richmond_spiders",
    "Rider": "rider_broncs",
    "Robert Morris": "robert_morris_colonials",
    "Rutgers": "rutgers_scarlet_knights",
    "SIU Edwardsville": "siu_edwardsville_cougars",
    "SIUE": "siu_edwardsville_cougars",
    "SMU": "smu_mustangs",
    "Sacramento St.": "sacramento_state_hornets",
    "Sacred Heart": "sacred_heart_pioneers",
    "Saint Francis": "saint_francis_red_flash",
    "Saint Joseph's": "saint_josephs_hawks",
    "Saint Louis": "saint_louis_billikens",
    "Saint Mary's": "saint_marys_gaels",
    "Saint Peter's": "saint_peters_peacocks",
    "Sam Houston St.": "sam_houston_bearkats",
    "Samford": "samford_bulldogs",
    "San Diego": "san_diego_toreros",
    "San Diego St.": "san_diego_state_aztecs",
    "San Francisco": "san_francisco_dons",
    "San Jose St.": "san_josé_state_spartans",
    "Santa Clara": "santa_clara_broncos",
    "Seattle": "seattle_u_redhawks",
    "Seton Hall": "seton_hall_pirates",
    "Siena": "siena_saints",
    "South Alabama": "south_alabama_jaguars",
    "South Carolina": "south_carolina_gamecocks",
    "South Carolina St.": "south_carolina_state_bulldogs",
    "South Dakota": "south_dakota_coyotes",
    "South Dakota St.": "south_dakota_state_jackrabbits",
    "Southeast Missouri St.": "southeast_missouri_state_redhawks",
    "South Florida": "south_florida_bulls",
    "Southeast Missouri": "southeast_missouri_state_redhawks",
    "Southeastern Louisiana": "se_louisiana_lions",
    "Southern": "southern_jaguars",
    "Southern Illinois": "southern_illinois_salukis",
    "Southern Indiana": "southern_indiana_screaming_eagles",
    "Southern Miss": "southern_miss_golden_eagles",
    "Southern Utah": "southern_utah_thunderbirds",
    "St. Bonaventure": "st_bonaventure_bonnies",
    "St. John's": "st_johns_red_storm",
    "St. Thomas": "st_thomas-minnesota_tommies",
    "Stanford": "stanford_cardinal",
    "Stephen F. Austin": "stephen_f_austin_lumberjacks",
    "Stetson": "stetson_hatters",
    "Stonehill": "stonehill_skyhawks",
    "Stony Brook": "stony_brook_seawolves",
    "Syracuse": "syracuse_orange",
    "TCU": "tcu_horned_frogs",
    "Tarleton St.": "tarleton_state_texans",
    "Temple": "temple_owls",
    "Tennessee": "tennessee_volunteers",
    "Tennessee Martin": "ut_martin_skyhawks",
    "Tennessee St.": "tennessee_state_tigers",
    "Tennessee Tech": "tennessee_tech_golden_eagles",
    "Texas": "texas_longhorns",
    "Texas A&M": "texas_am_aggies",
    "Texas A&M Corpus Chris": "texas_am-corpus_christi_islanders",
    "Texas Southern": "texas_southern_tigers",
    "Texas St.": "texas_state_bobcats",
    "Texas Tech": "texas_tech_red_raiders",
    "The Citadel": "citadel_bulldogs",
    "Toledo": "toledo_rockets",
    "Towson": "towson_tigers",
    "Troy": "troy_trojans",
    "Tulane": "tulane_green_wave",
    "Tulsa": "tulsa_golden_hurricane",
    "UAB": "uab_blazers",
    "UC Davis": "uc_davis_aggies",
    "UC Irvine": "uc_irvine_anteaters",
    "UC Riverside": "uc_riverside_highlanders",
    "UC San Diego": "uc_san_diego_tritons",
    "UC Santa Barbara": "uc_santa_barbara_gauchos",
    "UCF": "ucf_knights",
    "UCLA": "ucla_bruins",
    "UMBC": "umbc_retrievers",
    "UMKC": "kansas_city_roos",
    "UMass Lowell": "umass_lowell_river_hawks",
    "UNC Asheville": "unc_asheville_bulldogs",
    "UNC Greensboro": "unc_greensboro_spartans",
    "UNC Wilmington": "unc_wilmington_seahawks",
    "UNLV": "unlv_rebels",
    "USC": "usc_trojans",
    "USC Upstate": "south_carolina_upstate_spartans",
    "UT Arlington": "ut_arlington_mavericks",
    "UT Rio Grande Valley": "ut_rio_grande_valley_vaqueros",
    "UTEP": "utep_miners",
    "UTSA": "utsa_roadrunners",
    "Utah": "utah_utes",
    "Utah St.": "utah_state_aggies",
    "Utah Tech": "utah_tech_trailblazers",
    "Utah Valley": "utah_valley_wolverines",
    "VCU": "vcu_rams",
    "VMI": "vmi_keydets",
    "Valparaiso": "valparaiso_beacons",
    "Vanderbilt": "vanderbilt_commodores",
    "Vermont": "vermont_catamounts",
    "Villanova": "villanova_wildcats",
    "Virginia": "virginia_cavaliers",
    "Virginia Tech": "virginia_tech_hokies",
    "Wagner": "wagner_seahawks",
    "Wake Forest": "wake_forest_demon_deacons",
    "Washington": "washington_huskies",
    "Washington St.": "washington_state_cougars",
    "Weber St.": "weber_state_wildcats",
    "West Georgia": "west_georgia_wolves",
    "West Virginia": "west_virginia_mountaineers",
    "Western Carolina": "western_carolina_catamounts",
    "Western Illinois": "western_illinois_leathernecks",
    "Western Kentucky": "western_kentucky_hilltoppers",
    "Western Michigan": "western_michigan_broncos",
    "Wichita St.": "wichita_state_shockers",
    "William & Mary": "william_mary_tribe",
    "Winthrop": "winthrop_eagles",
    "Wisconsin": "wisconsin_badgers",
    "Wofford": "wofford_terriers",
    "Wright St.": "wright_state_raiders",
    "Wyoming": "wyoming_cowboys",
    "Xavier": "xavier_musketeers",
    "Yale": "yale_bulldogs",
    "Youngstown St.": "youngstown_state_penguins",
}

# Update teams
updated = 0
not_found = []
mismatches = []

for team in Team.objects.all():
    logo_stem = TEAM_TO_LOGO_STEM.get(team.name)
    
    if logo_stem is None:
        not_found.append(team.name)
        team.logo_url = None
        team.save(update_fields=['logo_url'])
        print(f"[NO LOGO] {team.name}")
        continue
    
    if logo_stem in logo_files:
        logo_filename = logo_files[logo_stem]
        team.logo_url = f'/logos/{logo_filename}'
        team.save(update_fields=['logo_url'])
        updated += 1
        print(f"[OK] {team.name} -> {logo_filename}")
    else:
        not_found.append(team.name)
        mismatches.append((team.name, logo_stem))
        print(f"[MISMATCH] {team.name} -> expected '{logo_stem}.png' but not found")

print(f"\n{'='*60}")
print(f"Updated: {updated} teams")
print(f"Not found/Mismatch: {len(not_found)} teams")

if mismatches:
    print("\nMismatched teams (check these manually):")
    for name, expected in mismatches:
        print(f"  {name} -> expected '{expected}.png'")
