import type { MetricDefinition } from '@/types';

export const metricDefinitions: MetricDefinition[] = [
  {
    id: 'adj_em',
    name: 'Adjusted Efficiency Margin (Adj EM)',
    category: 'Efficiency',
    definition: 'Net efficiency rating adjusted for opponent quality and tempo.',
    formula: 'Adj\,EM = Adj\,O - Adj\,D',
    interpretation: 'Higher values indicate better overall team quality.',
    range: '0 to 40+',
    higherIsBetter: true,
  },
  {
    id: 'adj_o',
    name: 'Adjusted Offensive Efficiency (Adj O)',
    category: 'Efficiency',
    definition: 'Points scored per 100 possessions adjusted for opponent strength.',
    formula: 'Adj\,O = 100 \times \frac{Points}{Possessions}',
    interpretation: 'Higher values indicate better offensive performance.',
    range: '95 to 125+',
    higherIsBetter: true,
  },
  {
    id: 'adj_d',
    name: 'Adjusted Defensive Efficiency (Adj D)',
    category: 'Efficiency',
    definition: 'Points allowed per 100 possessions adjusted for opponent strength.',
    formula: 'Adj\,D = 100 \times \frac{Opp\,Points}{Possessions}',
    interpretation: 'Lower values indicate better defense.',
    range: '85 to 115',
    higherIsBetter: false,
  },
  {
    id: 'tempo',
    name: 'Adjusted Tempo',
    category: 'Pace',
    definition: 'Estimated possessions per 40 minutes, adjusted for opponent pace.',
    formula: 'Tempo = \frac{Possessions}{Minutes} \times 40',
    interpretation: 'Higher values indicate faster pace of play.',
    range: '60 to 75',
    higherIsBetter: false,
  },
  {
    id: 'efg',
    name: 'Effective Field Goal % (eFG%)',
    category: 'Shooting',
    definition: 'Field goal percentage adjusted for 3-point shots being worth more.',
    formula: 'eFG\% = \frac{FG + 0.5 \times 3P}{FGA}',
    interpretation: 'Higher values indicate more efficient shooting.',
    range: '45% to 60%',
    higherIsBetter: true,
  },
  {
    id: 'tov',
    name: 'Turnover Rate (TOV%)',
    category: 'Ball Security',
    definition: 'Turnovers per 100 possessions.',
    formula: 'TOV\% = 100 \times \frac{TOV}{Possessions}',
    interpretation: 'Lower values indicate better ball security.',
    range: '12% to 20%',
    higherIsBetter: false,
  },
  {
    id: 'orb',
    name: 'Offensive Rebound % (ORB%)',
    category: 'Rebounding',
    definition: 'Percentage of available offensive rebounds secured.',
    formula: 'ORB\% = 100 \times \frac{ORB}{ORB + Opp\,DRB}',
    interpretation: 'Higher values indicate better offensive rebounding.',
    range: '25% to 40%',
    higherIsBetter: true,
  },
  {
    id: 'ftr',
    name: 'Free Throw Rate (FTR)',
    category: 'Fouls',
    definition: 'Free throws attempted per field goal attempt.',
    formula: 'FTR = \frac{FTA}{FGA}',
    interpretation: 'Higher values indicate more frequent trips to the line.',
    range: '0.20 to 0.45',
    higherIsBetter: true,
  },
  {
    id: 'ffi',
    name: 'Four Factor Index (FFI)',
    category: 'Composite',
    definition: 'Weighted composite of the Four Factors: eFG%, TOV%, ORB%, FTR.',
    formula: 'FFI = 0.4\,eFG + 0.2\,(1-TOV) + 0.2\,ORB + 0.2\,FTR',
    interpretation: 'Higher values indicate stronger overall four-factor performance.',
    range: '40 to 70',
    higherIsBetter: true,
  },
];
