# Generated by Django 5.0.1 on 2026-05-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0057_rename_core_scenar_team_id_from_sea_idx_core_scenar_team_id_8181dc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(db_index=True)),
                ('model_version', models.CharField(max_length=50)),
                ('period_type', models.CharField(choices=[('season', 'Full Season'), ('last_7', 'Last 7 Days'), ('last_30', 'Last 30 Days'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('games_evaluated', models.IntegerField(default=0)),
                ('winner_accuracy', models.FloatField(default=0.0)),
                ('spread_mae', models.FloatField(default=0.0)),
                ('score_mae', models.FloatField(default=0.0)),
                ('total_mae', models.FloatField(default=0.0)),
                ('average_margin_bias', models.FloatField(default=0.0)),
                ('brier_score', models.FloatField(default=0.0)),
                ('log_loss', models.FloatField(blank=True, null=True)),
                ('upset_predictions', models.IntegerField(default=0)),
                ('upset_hits', models.IntegerField(default=0)),
                ('upset_precision', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(db_index=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('snapshot_type', models.CharField(default='pregame', max_length=30)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('projected_home_score', models.FloatField()),
                ('projected_away_score', models.FloatField()),
                ('projected_home_margin', models.FloatField()),
                ('projected_total', models.FloatField()),
                ('home_win_probability', models.FloatField()),
                ('away_win_probability', models.FloatField()),
                ('home_adj_o', models.FloatField(blank=True, null=True)),
                ('home_adj_d', models.FloatField(blank=True, null=True)),
                ('away_adj_o', models.FloatField(blank=True, null=True)),
                ('away_adj_d', models.FloatField(blank=True, null=True)),
                ('nat_avg_ortg', models.FloatField(blank=True, null=True)),
                ('hca_points', models.FloatField(blank=True, null=True)),
                ('sigma_used', models.FloatField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to='core.game')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.team')),
                ('predicted_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(db_index=True)),
                ('actual_home_score', models.IntegerField()),
                ('actual_away_score', models.IntegerField()),
                ('actual_home_margin', models.IntegerField()),
                ('actual_total', models.IntegerField()),
                ('winner_correct', models.BooleanField()),
                ('margin_error', models.FloatField()),
                ('margin_abs_error', models.FloatField()),
                ('home_score_error', models.FloatField()),
                ('away_score_error', models.FloatField()),
                ('home_score_abs_error', models.FloatField()),
                ('away_score_abs_error', models.FloatField()),
                ('avg_score_abs_error', models.FloatField()),
                ('total_error', models.FloatField()),
                ('total_abs_error', models.FloatField()),
                ('brier_score', models.FloatField()),
                ('log_loss', models.FloatField(blank=True, null=True)),
                ('predicted_upset', models.BooleanField(default=False)),
                ('actual_upset', models.BooleanField(default=False)),
                ('upset_correct', models.BooleanField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='core.game')),
                ('prediction_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='validation.predictionsnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='validationsummary',
            constraint=models.UniqueConstraint(fields=('season_year', 'model_version', 'period_type'), name='unique_validation_summary'),
        ),
        migrations.AddIndex(
            model_name='predictionsnapshot',
            index=models.Index(fields=['season_year', 'is_locked'], name='validation__season__7734f3_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionsnapshot',
            index=models.Index(fields=['season_year', 'model_version'], name='validation__season__7f1bf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictionsnapshot',
            constraint=models.UniqueConstraint(fields=('game', 'model_version'), name='unique_snapshot_per_game_version'),
        ),
        migrations.AddIndex(
            model_name='gamevalidationresult',
            index=models.Index(fields=['season_year'], name='validation__season__fe88eb_idx'),
        ),
        migrations.AddIndex(
            model_name='gamevalidationresult',
            index=models.Index(fields=['season_year', 'winner_correct'], name='validation__season__99d033_idx'),
        ),
    ]
