# Generated by Django 5.0.1 on 2026-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dataset_name', models.CharField(max_length=100)),
                ('confederation', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=2)),
                ('is_host', models.BooleanField(default=False)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('fifa_rank', models.IntegerField(default=0)),
                ('elo_rating', models.FloatField(default=1500.0)),
                ('elo_rank', models.IntegerField(default=0)),
                ('elo_vs_fifa', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['elo_rank'],
            },
        ),
    ]
