# Generated by Django 5.0.1 on 2026-06-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_cup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupteam',
            name='fifa_points',
            field=models.FloatField(default=0.0),
        ),
    ]
