"""
Conference mapping utilities for CBB Analytics.

CONF_MAP maps team slugs → conference codes (2025-26 season).

Conference tier constants:
  POWER_CONFS     – true Power 5 + Big East (ACC, B10, B12, SEC, BE)
  HIGH_MID_CONFS  – elite non-power conferences (WCC, MWC, A10, Amer)

Two classification functions with different granularity:

  get_conf_group(slug) → 'power' | 'mid_major'
      Coarse two-tier classifier used for the 15 broad baseline archetypes.
      HIGH_MID_CONFS is pooled into 'mid_major' here to guarantee bucket mass.

  get_conf_detail(slug) → 'power' | 'high_mid' | 'mid_major'
      Fine-grained three-tier classifier used for Tier 2 optional archetypes.
      Returns 'high_mid' for WCC/MWC/A10/Amer teams (n is large enough for
      dedicated archetype buckets at this level).
      Returns 'mid_major' for all remaining non-power conferences.
"""

# --------------------------------------------------------------------------- #
# Canonical slug → conference code mapping (2025-26 season)
# --------------------------------------------------------------------------- #

CONF_MAP: dict[str, str] = {
    # Big Ten (B10)
    "michigan": "B10",
    "michigan-state": "B10",
    "michigan-st": "B10",
    "ohio-state": "B10",
    "ohio-st": "B10",
    "purdue": "B10",
    "illinois": "B10",
    "indiana": "B10",
    "iowa": "B10",
    "wisconsin": "B10",
    "maryland": "B10",
    "penn-state": "B10",
    "penn-st": "B10",
    "rutgers": "B10",
    "nebraska": "B10",
    "minnesota": "B10",
    "northwestern": "B10",
    "ucla": "B10",
    "usc": "B10",
    "oregon": "B10",
    "washington": "B10",
    # ACC
    "duke": "ACC",
    "north-carolina": "ACC",
    "unc": "ACC",
    "virginia": "ACC",
    "louisville": "ACC",
    "syracuse": "ACC",
    "florida-state": "ACC",
    "florida-st": "ACC",
    "nc-state": "ACC",
    "clemson": "ACC",
    "wake-forest": "ACC",
    "miami": "ACC",
    "miami-fl": "ACC",
    "miami-(fl)": "ACC",
    "georgia-tech": "ACC",
    "boston-college": "ACC",
    "virginia-tech": "ACC",
    "pitt": "ACC",
    "pittsburgh": "ACC",
    "notre-dame": "ACC",
    "california": "ACC",
    "stanford": "ACC",
    "smu": "ACC",
    # Big 12 (B12)
    "kansas": "B12",
    "baylor": "B12",
    "iowa-st": "B12",
    "iowa-state": "B12",
    "texas-tech": "B12",
    "tcu": "B12",
    "oklahoma-state": "B12",
    "oklahoma-st": "B12",
    "west-virginia": "B12",
    "kansas-state": "B12",
    "kansas-st": "B12",
    "houston": "B12",
    "cincinnati": "B12",
    "ucf": "B12",
    "byu": "B12",
    "colorado": "B12",
    "arizona": "B12",
    "arizona-state": "B12",
    "arizona-st": "B12",
    "utah": "B12",
    # SEC
    "kentucky": "SEC",
    "florida": "SEC",
    "tennessee": "SEC",
    "arkansas": "SEC",
    "alabama": "SEC",
    "auburn": "SEC",
    "lsu": "SEC",
    "mississippi-state": "SEC",
    "mississippi-st": "SEC",
    "georgia": "SEC",
    "missouri": "SEC",
    "south-carolina": "SEC",
    "vanderbilt": "SEC",
    "texas": "SEC",
    "texas-am": "SEC",
    "texas-a-m": "SEC",
    "texas-a&m": "SEC",
    "ole-miss": "SEC",
    "mississippi": "SEC",
    "oklahoma": "SEC",
    # Big East (BE)
    "connecticut": "BE",
    "uconn": "BE",
    "villanova": "BE",
    "creighton": "BE",
    "marquette": "BE",
    "st-johns": "BE",
    "st-john-s": "BE",
    "st-john's": "BE",
    "providence": "BE",
    "xavier": "BE",
    "butler": "BE",
    "seton-hall": "BE",
    "depaul": "BE",
    "georgetown": "BE",
    # WCC
    "gonzaga": "WCC",
    "saint-marys": "WCC",
    "saint-mary-s": "WCC",
    "saint-mary's": "WCC",
    "st-marys": "WCC",
    "san-francisco": "WCC",
    "santa-clara": "WCC",
    "loyola-marymount": "WCC",
    "pepperdine": "WCC",
    "portland": "WCC",
    "pacific": "WCC",
    "san-diego": "WCC",
    "oregon-st": "WCC",
    "washington-st": "WCC",
    "seattle": "WCC",
    "seattle-u": "WCC",
    # Mountain West (MWC)
    "utah-st": "MWC",
    "utah-state": "MWC",
    "san-diego-state": "MWC",
    "san-diego-st": "MWC",
    "sdsu": "MWC",
    "nevada": "MWC",
    "unlv": "MWC",
    "colorado-state": "MWC",
    "colorado-st": "MWC",
    "new-mexico": "MWC",
    "boise-state": "MWC",
    "boise-st": "MWC",
    "wyoming": "MWC",
    "fresno-state": "MWC",
    "fresno-st": "MWC",
    "air-force": "MWC",
    "san-jose-state": "MWC",
    "san-jose-st": "MWC",
    "grand-canyon": "MWC",
    # Atlantic 10 (A10)
    "saint-louis": "A10",
    "st-louis": "A10",
    "dayton": "A10",
    "vcu": "A10",
    "richmond": "A10",
    "st-bonaventure": "A10",
    "saint-bonaventure": "A10",
    "davidson": "A10",
    "rhode-island": "A10",
    "george-mason": "A10",
    "fordham": "A10",
    "st-josephs": "A10",
    "saint-josephs": "A10",
    "saint-joseph's": "A10",
    "la-salle": "A10",
    "duquesne": "A10",
    "george-washington": "A10",
    "loyola-chicago": "A10",
    # American Athletic (Amer)
    "memphis": "Amer",
    "temple": "Amer",
    "wichita-state": "Amer",
    "wichita-st": "Amer",
    "east-carolina": "Amer",
    "south-florida": "Amer",
    "tulsa": "Amer",
    "tulane": "Amer",
    "north-texas": "Amer",
    "uab": "Amer",
    "charlotte": "Amer",
    "florida-atlantic": "Amer",
    "utsa": "Amer",
    "rice": "Amer",
    # Conference USA (CUSA)
    "louisiana-tech": "CUSA",
    "western-kentucky": "CUSA",
    "middle-tennessee": "CUSA",
    "jacksonville-state": "CUSA",
    "jacksonville-st": "CUSA",
    "kennesaw-state": "CUSA",
    "kennesaw-st": "CUSA",
    "liberty": "CUSA",
    "new-mexico-state": "CUSA",
    "new-mexico-st": "CUSA",
    "sam-houston-state": "CUSA",
    "sam-houston-st": "CUSA",
    "fiu": "CUSA",
    "utep": "CUSA",
    "delaware": "CUSA",
    "missouri-state": "CUSA",
    "missouri-st": "CUSA",
    # Missouri Valley (MVC)
    "illinois-state": "MVC",
    "illinois-st": "MVC",
    "indiana-state": "MVC",
    "indiana-st": "MVC",
    "drake": "MVC",
    "bradley": "MVC",
    "northern-iowa": "MVC",
    "southern-illinois": "MVC",
    "valparaiso": "MVC",
    "belmont": "MVC",
    "murray-state": "MVC",
    "murray-st": "MVC",
    "evansville": "MVC",
    "uic": "MVC",
    "illinois-chicago": "MVC",
    # Big West (BW)
    "hawaii": "BW",
    "uc-irvine": "BW",
    "uc-davis": "BW",
    "uc-santa-barbara": "BW",
    "ucsb": "BW",
    "cal-poly": "BW",
    "cal-state-northridge": "BW",
    "cal-st-northridge": "BW",
    "csun": "BW",
    "cal-state-fullerton": "BW",
    "cal-st-fullerton": "BW",
    "uc-riverside": "BW",
    "cal-state-bakersfield": "BW",
    "cal-st-bakersfield": "BW",
    "long-beach-state": "BW",
    "long-beach-st": "BW",
    "uc-san-diego": "BW",
    # Summit League (Sum)
    "south-dakota-state": "Sum",
    "south-dakota-st": "Sum",
    "north-dakota-state": "Sum",
    "north-dakota-st": "Sum",
    "oral-roberts": "Sum",
    "south-dakota": "Sum",
    "north-dakota": "Sum",
    "denver": "Sum",
    "omaha": "Sum",
    "nebraska-omaha": "Sum",
    "kansas-city": "Sum",
    "umkc": "Sum",
    "st-thomas": "Sum",
    # WAC
    "utah-valley": "WAC",
    "abilene-christian": "WAC",
    "southern-utah": "WAC",
    "ut-arlington": "WAC",
    "tarleton-state": "WAC",
    "tarleton-st": "WAC",
    "cal-baptist": "WAC",
    "california-baptist": "WAC",
    "utah-tech": "WAC",
    # Horizon League (Horz)
    "wright-state": "Horz",
    "wright-st": "Horz",
    "northern-kentucky": "Horz",
    "cleveland-state": "Horz",
    "cleveland-st": "Horz",
    "oakland": "Horz",
    "youngstown-state": "Horz",
    "youngstown-st": "Horz",
    "milwaukee": "Horz",
    "robert-morris": "Horz",
    "iupui": "Horz",
    "iu-indy": "Horz",
    "purdue-fort-wayne": "Horz",
    "green-bay": "Horz",
    "detroit-mercy": "Horz",
    # MAAC
    "iona": "MAAC",
    "marist": "MAAC",
    "manhattan": "MAAC",
    "quinnipiac": "MAAC",
    "fairfield": "MAAC",
    "rider": "MAAC",
    "siena": "MAAC",
    "niagara": "MAAC",
    "canisius": "MAAC",
    "merrimack": "MAAC",
    "mount-st-marys": "MAAC",
    "mount-st-mary-s": "MAAC",
    "mount-st-mary's": "MAAC",
    "sacred-heart": "MAAC",
    "saint-peters": "MAAC",
    "saint-peter-s": "MAAC",
    "saint-peter's": "MAAC",
    "st-peters": "MAAC",
    # MAC
    "toledo": "MAC",
    "akron": "MAC",
    "bowling-green": "MAC",
    "kent-state": "MAC",
    "kent-st": "MAC",
    "miami-oh": "MAC",
    "miami-(oh)": "MAC",
    "ohio": "MAC",
    "ball-state": "MAC",
    "ball-st": "MAC",
    "buffalo": "MAC",
    "central-michigan": "MAC",
    "eastern-michigan": "MAC",
    "eastern-mich": "MAC",
    "massachusetts": "MAC",
    "umass": "MAC",
    "northern-illinois": "MAC",
    "western-michigan": "MAC",
    "western-mich": "MAC",
    # NEC
    "central-connecticut": "NEC",
    "central-connecticut-st": "NEC",
    "liu": "NEC",
    "wagner": "NEC",
    "stonehill": "NEC",
    "le-moyne": "NEC",
    "fairleigh-dickinson": "NEC",
    "chicago-state": "NEC",
    "chicago-st": "NEC",
    "saint-francis": "NEC",
    "mercyhurst": "NEC",
    "new-haven": "NEC",
    # Big Sky (BSky)
    "montana": "BSky",
    "montana-state": "BSky",
    "montana-st": "BSky",
    "weber-state": "BSky",
    "weber-st": "BSky",
    "idaho": "BSky",
    "idaho-state": "BSky",
    "idaho-st": "BSky",
    "northern-colorado": "BSky",
    "portland-state": "BSky",
    "portland-st": "BSky",
    "eastern-washington": "BSky",
    "northern-arizona": "BSky",
    "sacramento-state": "BSky",
    "sacramento-st": "BSky",
    # OVC
    "morehead-state": "OVC",
    "morehead-st": "OVC",
    "tennessee-state": "OVC",
    "tennessee-st": "OVC",
    "ut-martin": "OVC",
    "tennessee-martin": "OVC",
    "tennessee-tech": "OVC",
    "lindenwood": "OVC",
    "siu-edwardsville": "OVC",
    "little-rock": "OVC",
    "western-illinois": "OVC",
    "eastern-illinois": "OVC",
    "southeast-missouri-st": "OVC",
    "southern-indiana": "OVC",
    # CAA
    "charleston": "CAA",
    "hofstra": "CAA",
    "drexel": "CAA",
    "towson": "CAA",
    "unc-wilmington": "CAA",
    "monmouth": "CAA",
    "stony-brook": "CAA",
    "elon": "CAA",
    "william-mary": "CAA",
    "william-&-mary": "CAA",
    "hampton": "CAA",
    "campbell": "CAA",
    "north-carolina-at": "CAA",
    "north-carolina-a&t": "CAA",
    "nc-at": "CAA",
    "nc-a&t": "CAA",
    "northeastern": "CAA",
    # Southern (SC)
    "furman": "SC",
    "wofford": "SC",
    "unc-greensboro": "SC",
    "samford": "SC",
    "east-tennessee-state": "SC",
    "east-tennessee-st": "SC",
    "etsu": "SC",
    "chattanooga": "SC",
    "the-citadel": "SC",
    "citadel": "SC",
    "vmi": "SC",
    "western-carolina": "SC",
    "mercer": "SC",
    # Sun Belt (SB)
    "james-madison": "SB",
    "coastal-carolina": "SB",
    "troy": "SB",
    "georgia-state": "SB",
    "georgia-st": "SB",
    "georgia-southern": "SB",
    "app-state": "SB",
    "appalachian-state": "SB",
    "appalachian-st": "SB",
    "louisiana": "SB",
    "marshall": "SB",
    "old-dominion": "SB",
    "southern-miss": "SB",
    "southern-mississippi": "SB",
    "arkansas-state": "SB",
    "arkansas-st": "SB",
    "ulm": "SB",
    "louisiana-monroe": "SB",
    "texas-state": "SB",
    "texas-st": "SB",
    "south-alabama": "SB",
    # Southland (Slnd)
    "mcneese-state": "Slnd",
    "mcneese-st": "Slnd",
    "mcneese": "Slnd",
    "nicholls-state": "Slnd",
    "nicholls-st": "Slnd",
    "nicholls": "Slnd",
    "northwestern-state": "Slnd",
    "northwestern-st": "Slnd",
    "southeastern-louisiana": "Slnd",
    "texas-am-commerce": "Slnd",
    "east-texas-a&m": "Slnd",
    "east-texas-am": "Slnd",
    "stephen-f-austin": "Slnd",
    "houston-christian": "Slnd",
    "incarnate-word": "Slnd",
    "lamar": "Slnd",
    "new-orleans": "Slnd",
    "texas-a&m-corpus-chris": "Slnd",
    "texas-am-corpus-chris": "Slnd",
    "ut-rio-grande-valley": "Slnd",
    # ASUN
    "lipscomb": "ASun",
    "jacksonville": "ASun",
    "fgcu": "ASun",
    "florida-gulf-coast": "ASun",
    "stetson": "ASun",
    "north-florida": "ASun",
    "queens": "ASun",
    "eastern-kentucky": "ASun",
    "austin-peay": "ASun",
    "central-arkansas": "ASun",
    "bellarmine": "ASun",
    "north-alabama": "ASun",
    "west-georgia": "ASun",
    # America East (AE)
    "vermont": "AE",
    "bryant": "AE",
    "umbc": "AE",
    "umass-lowell": "AE",
    "binghamton": "AE",
    "new-hampshire": "AE",
    "unh": "AE",
    "maine": "AE",
    "albany": "AE",
    "njit": "AE",
    # Ivy League
    "princeton": "Ivy",
    "yale": "Ivy",
    "harvard": "Ivy",
    "cornell": "Ivy",
    "penn": "Ivy",
    "pennsylvania": "Ivy",
    "brown": "Ivy",
    "columbia": "Ivy",
    "dartmouth": "Ivy",
    # Patriot League (Pat)
    "colgate": "Pat",
    "army": "Pat",
    "navy": "Pat",
    "bucknell": "Pat",
    "holy-cross": "Pat",
    "lehigh": "Pat",
    "lafayette": "Pat",
    "boston-university": "Pat",
    "american": "Pat",
    "loyola-maryland": "Pat",
    "loyola-md": "Pat",
    # MEAC
    "norfolk-state": "MEAC",
    "norfolk-st": "MEAC",
    "howard": "MEAC",
    "north-carolina-central": "MEAC",
    "nc-central": "MEAC",
    "morgan-state": "MEAC",
    "morgan-st": "MEAC",
    "south-carolina-state": "MEAC",
    "south-carolina-st": "MEAC",
    "coppin-state": "MEAC",
    "coppin-st": "MEAC",
    "delaware-state": "MEAC",
    "delaware-st": "MEAC",
    "maryland-eastern-shore": "MEAC",
    "umes": "MEAC",
    # SWAC
    "alabama-state": "SWAC",
    "alabama-st": "SWAC",
    "alabama-a&m": "SWAC",
    "alabama-am": "SWAC",
    "alcorn-state": "SWAC",
    "alcorn-st": "SWAC",
    "arkansas-pine-bluff": "SWAC",
    "bethune-cookman": "SWAC",
    "florida-am": "SWAC",
    "florida-a&m": "SWAC",
    "famu": "SWAC",
    "grambling-state": "SWAC",
    "grambling-st": "SWAC",
    "jackson-state": "SWAC",
    "jackson-st": "SWAC",
    "mississippi-valley-state": "SWAC",
    "mississippi-valley-st": "SWAC",
    "prairie-view-am": "SWAC",
    "prairie-view-a&m": "SWAC",
    "southern": "SWAC",
    "texas-southern": "SWAC",
    # Big South (BSth)
    "high-point": "BSth",
    "radford": "BSth",
    "longwood": "BSth",
    "gardner-webb": "BSth",
    "winthrop": "BSth",
    "charleston-southern": "BSth",
    "presbyterian": "BSth",
    "unc-asheville": "BSth",
    "usc-upstate": "BSth",
}

# --------------------------------------------------------------------------- #
# Conference tier groups
# --------------------------------------------------------------------------- #

# True Power 6 + Big East  (ACC, B10, B12, SEC, BE)
POWER_CONFS: frozenset[str] = frozenset({"ACC", "B10", "B12", "SEC", "BE"})

# High mid-major: elite non-power conferences
HIGH_MID_CONFS: frozenset[str] = frozenset({"WCC", "MWC", "A10", "Amer"})


def get_team_conference(team_slug: str) -> str:
    """
    Return the raw conference code for a team slug (e.g. 'ACC', 'WCC', 'MAAC').

    Used for per-conference archetype generation.
    Unknown slugs return 'Unknown'.
    """
    return CONF_MAP.get(team_slug.lower(), "Unknown")


def get_conf_group(team_slug: str) -> str:
    """
    Coarse 2-tier classifier: 'power' | 'mid_major'.

    HIGH_MID_CONFS (WCC, MWC, A10, Amer) are pooled into 'mid_major' to
    ensure adequate bucket mass for the 15 broad baseline archetypes.
    Unknown slugs default to 'mid_major'.
    """
    conf = CONF_MAP.get(team_slug.lower(), None)
    if conf is None:
        return "mid_major"
    if conf in POWER_CONFS:
        return "power"
    return "mid_major"


def get_conf_detail(team_slug: str) -> str:
    """
    Fine-grained 3-tier classifier: 'power' | 'high_mid' | 'mid_major'.

    Used for Tier 2 optional archetypes.  Returns 'high_mid' for WCC, MWC,
    A10, and Amer teams — conferences whose combined bucket sizes support
    dedicated archetype generation.  All other non-power conferences return
    'mid_major'.  Unknown slugs default to 'mid_major'.
    """
    conf = CONF_MAP.get(team_slug.lower(), None)
    if conf is None:
        return "mid_major"
    if conf in POWER_CONFS:
        return "power"
    if conf in HIGH_MID_CONFS:
        return "high_mid"
    return "mid_major"
