# Generated by Django 5.0.1 on 2026-04-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(db_index=True, help_text='NBA.com canonical player ID', unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NBASeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='Ending year (2026 for 2025-26)', unique=True)),
                ('display_name', models.CharField(help_text='Human-readable, e.g. 2025-26', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_team_id', models.IntegerField(db_index=True, help_text='NBA.com canonical team ID', unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(help_text='Full franchise name, e.g. Boston Celtics', max_length=100)),
                ('abbreviation', models.CharField(help_text='e.g. BOS', max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('conference', models.CharField(choices=[('East', 'Eastern Conference'), ('West', 'Western Conference')], max_length=10)),
                ('division', models.CharField(max_length=50)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NBAGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, help_text='NBA.com game ID', max_length=20, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('arena', models.CharField(blank=True, max_length=150)),
                ('season_type', models.CharField(choices=[('preseason', 'Preseason'), ('regular', 'Regular Season'), ('play_in', 'Play-In'), ('playoffs', 'Playoffs')], default='regular', max_length=20)),
                ('competition', models.CharField(choices=[('regular', 'Regular'), ('nba_cup_group', 'NBA Cup Group Stage'), ('nba_cup_qf', 'NBA Cup Quarterfinal'), ('nba_cup_sf', 'NBA Cup Semifinal'), ('nba_cup_final', 'NBA Cup Championship')], default='regular', max_length=20)),
                ('counts_toward_regular_season', models.BooleanField(db_index=True, default=True, help_text='False only for NBA Cup Championship and non-regular season games.')),
                ('status', models.CharField(default='Scheduled', help_text='Final | Scheduled | Live', max_length=20)),
                ('rest_days_home', models.IntegerField(blank=True, help_text='Days since last game for home team', null=True)),
                ('rest_days_away', models.IntegerField(blank=True, help_text='Days since last game for away team', null=True)),
                ('home_b2b', models.BooleanField(default=False)),
                ('away_b2b', models.BooleanField(default=False)),
                ('box_score_synced', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='nba.nbaseason')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='nba.nbateam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='nba.nbateam')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NBAPlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_played', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('reb', models.IntegerField(blank=True, null=True)),
                ('ast', models.IntegerField(blank=True, null=True)),
                ('stl', models.IntegerField(blank=True, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('tov', models.IntegerField(blank=True, null=True)),
                ('fgm', models.IntegerField(blank=True, null=True)),
                ('fga', models.IntegerField(blank=True, null=True)),
                ('fg3m', models.IntegerField(blank=True, null=True)),
                ('fg3a', models.IntegerField(blank=True, null=True)),
                ('ftm', models.IntegerField(blank=True, null=True)),
                ('fta', models.IntegerField(blank=True, null=True)),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='nba.nbagame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='nba.nbaplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_stats', to='nba.nbateam')),
            ],
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='nba.nbateam'),
        ),
        migrations.CreateModel(
            name='NBATeamGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home', models.BooleanField()),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('opp_pts', models.IntegerField(blank=True, null=True)),
                ('fgm', models.IntegerField(blank=True, null=True)),
                ('fga', models.IntegerField(blank=True, null=True)),
                ('fg3m', models.IntegerField(blank=True, null=True)),
                ('fg3a', models.IntegerField(blank=True, null=True)),
                ('ftm', models.IntegerField(blank=True, null=True)),
                ('fta', models.IntegerField(blank=True, null=True)),
                ('oreb', models.IntegerField(blank=True, null=True)),
                ('dreb', models.IntegerField(blank=True, null=True)),
                ('tov', models.IntegerField(blank=True, null=True)),
                ('poss', models.FloatField(blank=True, help_text='Estimated possessions', null=True)),
                ('raw_ortg', models.FloatField(blank=True, help_text='Raw offensive rating (pts/100 poss)', null=True)),
                ('raw_drtg', models.FloatField(blank=True, help_text='Raw defensive rating (opp pts/100 opp poss)', null=True)),
                ('adj_ortg', models.FloatField(blank=True, null=True)),
                ('adj_drtg', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='nba.nbagame')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='nba.nbateam')),
            ],
        ),
        migrations.CreateModel(
            name='NBATeamSeasonRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('adj_off', models.FloatField(blank=True, help_text='Opponent-adjusted offensive rating', null=True)),
                ('adj_def', models.FloatField(blank=True, help_text='Opponent-adjusted defensive rating', null=True)),
                ('adj_net', models.FloatField(blank=True, help_text='adj_off - adj_def', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Possessions per 48 min', null=True)),
                ('efg_pct', models.FloatField(blank=True, null=True)),
                ('opp_efg_pct', models.FloatField(blank=True, null=True)),
                ('tov_rate', models.FloatField(blank=True, null=True)),
                ('opp_tov_rate', models.FloatField(blank=True, null=True)),
                ('oreb_pct', models.FloatField(blank=True, null=True)),
                ('opp_oreb_pct', models.FloatField(blank=True, null=True)),
                ('fta_rate', models.FloatField(blank=True, null=True)),
                ('opp_fta_rate', models.FloatField(blank=True, null=True)),
                ('efg_margin', models.FloatField(blank=True, help_text='eFG% - Opp eFG%', null=True)),
                ('tov_edge', models.FloatField(blank=True, help_text='Opp TOV% - TOV%', null=True)),
                ('oreb_edge', models.FloatField(blank=True, help_text='OREB% - Opp OREB%', null=True)),
                ('fta_margin', models.FloatField(blank=True, help_text='FTA/FGA - Opp FTA/FGA', null=True)),
                ('ffi', models.FloatField(blank=True, help_text='PROVISIONAL Four Factor Index. See nba/ratings_config.py for weights.', null=True)),
                ('rank_adj_net', models.IntegerField(blank=True, help_text='Derived rank by adj_net. Not source of truth.', null=True)),
                ('rank_ffi', models.IntegerField(blank=True, help_text='Derived rank by FFI. Not source of truth.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ratings', to='nba.nbaseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_ratings', to='nba.nbateam')),
            ],
            options={
                'ordering': ['rank_adj_net'],
            },
        ),
        migrations.AddConstraint(
            model_name='nbaplayergamestats',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_nba_player_game_stats'),
        ),
        migrations.AddConstraint(
            model_name='nbateamgamestats',
            constraint=models.UniqueConstraint(fields=('game', 'team'), name='unique_nba_team_game_stats'),
        ),
        migrations.AddConstraint(
            model_name='nbateamseasonratings',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='unique_nba_team_season_ratings'),
        ),
    ]
