# Generated by Django 5.0.1 on 2026-04-02 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAModelCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('games_predicted', models.IntegerField(blank=True, help_text='Completed games where both teams have ratings', null=True)),
                ('correct_predictions', models.IntegerField(blank=True, null=True)),
                ('straight_up_accuracy', models.FloatField(blank=True, help_text='% correct (0-100)', null=True)),
                ('brier_score', models.FloatField(blank=True, help_text='Brier score (lower=better). Baseline ~0.25.', null=True)),
                ('log_loss', models.FloatField(blank=True, help_text='Log-loss (lower=better). Baseline ~0.693.', null=True)),
                ('ols_games', models.IntegerField(blank=True, help_text='Games used in the HCA/B2B OLS regression', null=True)),
                ('ols_r_squared', models.FloatField(blank=True, help_text='R² of OLS fit', null=True)),
                ('empirical_hca', models.FloatField(blank=True, help_text='OLS intercept ≈ empirical HCA in raw points', null=True)),
                ('configured_hca', models.FloatField(blank=True, help_text='Current ratings_config home_court_adj value', null=True)),
                ('ols_model_scale', models.FloatField(blank=True, help_text='OLS β₁ coefficient: how many raw score points per 1 pt/100 poss of adj_net advantage (should approach 1.0 as games accumulate)', null=True)),
                ('empirical_home_b2b_penalty', models.FloatField(blank=True, help_text='OLS β₂: raw-points penalty when home team is on B2B (negative value = home hurt)', null=True)),
                ('empirical_away_b2b_penalty', models.FloatField(blank=True, help_text='OLS β₃: raw-points penalty when away team is on B2B (positive = home benefits when away team is tired)', null=True)),
                ('configured_b2b_penalty', models.FloatField(blank=True, help_text='Current ratings_config b2b_penalty value', null=True)),
                ('ffi_teams_used', models.IntegerField(blank=True, help_text='Teams with complete four-factor data', null=True)),
                ('ffi_adj_net_r_squared', models.FloatField(blank=True, help_text='R² of four-factors → adj_net regression', null=True)),
                ('ffi_proposed_weight_efg', models.FloatField(blank=True, help_text='Data-driven eFG margin weight (sums to 1 with others)', null=True)),
                ('ffi_proposed_weight_tov', models.FloatField(blank=True, null=True)),
                ('ffi_proposed_weight_oreb', models.FloatField(blank=True, null=True)),
                ('ffi_proposed_weight_fta', models.FloatField(blank=True, null=True)),
                ('ffi_current_weight_efg', models.FloatField(blank=True, help_text='Currently configured eFG margin weight', null=True)),
                ('ffi_current_weight_tov', models.FloatField(blank=True, null=True)),
                ('ffi_current_weight_oreb', models.FloatField(blank=True, null=True)),
                ('ffi_current_weight_fta', models.FloatField(blank=True, null=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_calibration', to='nba.nbaseason')),
            ],
            options={
                'ordering': ['-season__year'],
            },
        ),
    ]
