# Generated by Django 5.0.1 on 2026-04-02 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_add_model_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAPlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gp', models.IntegerField(help_text='Games played')),
                ('mpg', models.FloatField(blank=True, help_text='Minutes per game', null=True)),
                ('pts', models.FloatField(blank=True, null=True)),
                ('reb', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('stl', models.FloatField(blank=True, null=True)),
                ('blk', models.FloatField(blank=True, null=True)),
                ('tov', models.FloatField(blank=True, null=True)),
                ('plus_minus', models.FloatField(blank=True, help_text='+/- per game', null=True)),
                ('fg_pct', models.FloatField(blank=True, help_text='FGM/FGA', null=True)),
                ('fg3_pct', models.FloatField(blank=True, help_text='3PM/3PA', null=True)),
                ('ft_pct', models.FloatField(blank=True, help_text='FTM/FTA', null=True)),
                ('fga_pg', models.FloatField(blank=True, help_text='FGA per game', null=True)),
                ('fg3a_pg', models.FloatField(blank=True, help_text='3PA per game', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='nba.nbaplayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_stats', to='nba.nbaseason')),
                ('team', models.ForeignKey(blank=True, help_text='Team the player spent the most minutes with this season', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_season_stats', to='nba.nbateam')),
            ],
            options={
                'ordering': ['-pts'],
            },
        ),
        migrations.AddConstraint(
            model_name='nbaplayerseasonstats',
            constraint=models.UniqueConstraint(fields=('player', 'season', 'team'), name='unique_nba_player_season_stats'),
        ),
    ]
