# Generated by Django 5.0.1 on 2026-04-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0003_add_player_season_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='ast_pct',
            field=models.FloatField(blank=True, help_text='Assist %', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='ast_to',
            field=models.FloatField(blank=True, help_text='Assist-to-turnover ratio', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='blk_pct',
            field=models.FloatField(blank=True, help_text='Block %', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='d_mpir',
            field=models.FloatField(blank=True, help_text='Defensive MPIR (= league_avg_drtg - E_DEF_RATING)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='dreb_pct',
            field=models.FloatField(blank=True, help_text='Defensive rebound %', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='dreb_pg',
            field=models.FloatField(blank=True, help_text='Defensive rebounds per game', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='efg_pct',
            field=models.FloatField(blank=True, help_text='Effective FG% (from NBA.com)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='fta_pg',
            field=models.FloatField(blank=True, help_text='FTA per game', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='ftm_pg',
            field=models.FloatField(blank=True, help_text='FTM per game', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='mpir',
            field=models.FloatField(blank=True, help_text='Macfax Player Impact Rating (= E_NET_RATING)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='o_mpir',
            field=models.FloatField(blank=True, help_text='Offensive MPIR (= E_OFF_RATING - league_avg_ortg)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_adj_d',
            field=models.FloatField(blank=True, help_text='Estimated adj defensive impact (NBA.com E_DEF_RATING)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_adj_em',
            field=models.FloatField(blank=True, help_text='Estimated adj net impact (NBA.com E_NET_RATING) = MPIR', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_adj_o',
            field=models.FloatField(blank=True, help_text='Estimated adj offensive impact (NBA.com E_OFF_RATING)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_drtg',
            field=models.FloatField(blank=True, help_text='On-court defensive rating (raw, per 100 poss)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_net',
            field=models.FloatField(blank=True, help_text='On-court net rating (raw)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_ortg',
            field=models.FloatField(blank=True, help_text='On-court offensive rating (raw, per 100 poss)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='on_court_poss',
            field=models.FloatField(blank=True, help_text='Possessions played (on-court)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='oreb_pct',
            field=models.FloatField(blank=True, help_text='Offensive rebound %', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='oreb_pg',
            field=models.FloatField(blank=True, help_text='Offensive rebounds per game', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='pie',
            field=models.FloatField(blank=True, help_text='Player Impact Estimate (NBA.com)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='stl_pct',
            field=models.FloatField(blank=True, help_text='Steal %', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='tov_pct',
            field=models.FloatField(blank=True, help_text='Turnover % (team TOV rate while on)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='ts_pct',
            field=models.FloatField(blank=True, help_text='True Shooting %', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='usg_pct',
            field=models.FloatField(blank=True, help_text='Usage rate', null=True),
        ),
    ]
