# Generated by Django 5.0.1 on 2026-05-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_add_nba_box_bpr'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nbaplayerseasonstats',
            name='unique_nba_player_season_stats',
        ),
        migrations.RemoveConstraint(
            model_name='nbateamseasonratings',
            name='unique_nba_team_season_ratings',
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='season_type',
            field=models.CharField(choices=[('preseason', 'Preseason'), ('regular', 'Regular Season'), ('play_in', 'Play-In'), ('playoffs', 'Playoffs')], db_index=True, default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='nbateamseasonratings',
            name='season_type',
            field=models.CharField(choices=[('preseason', 'Preseason'), ('regular', 'Regular Season'), ('play_in', 'Play-In'), ('playoffs', 'Playoffs')], db_index=True, default='regular', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='nbaplayerseasonstats',
            constraint=models.UniqueConstraint(fields=('player', 'season', 'team', 'season_type'), name='unique_nba_player_season_stats'),
        ),
        migrations.AddConstraint(
            model_name='nbateamseasonratings',
            constraint=models.UniqueConstraint(fields=('team', 'season', 'season_type'), name='unique_nba_team_season_ratings'),
        ),
    ]
