# Generated by Django 5.0.1 on 2026-05-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_nba_stage2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nbaplayergamestint',
            options={},
        ),
        migrations.RenameIndex(
            model_name='nbaplayergamestint',
            new_name='nba_nbaplay_game_id_f22847_idx',
            old_name='nba_pgstint_game_idx',
        ),
        migrations.RenameIndex(
            model_name='nbaplayergamestint',
            new_name='nba_nbaplay_player__a5916c_idx',
            old_name='nba_pgstint_player_idx',
        ),
        migrations.RenameIndex(
            model_name='nbaplayergamestint',
            new_name='nba_nbaplay_game_id_ee2c0c_idx',
            old_name='nba_pgstint_team_idx',
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='bpr',
            field=models.FloatField(blank=True, help_text='Final total BPR (obpr + dbpr)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='dbpr',
            field=models.FloatField(blank=True, help_text='Final defensive BPR (prior-informed RAPM)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='obpr',
            field=models.FloatField(blank=True, help_text='Final offensive BPR (prior-informed RAPM)', null=True),
        ),
        migrations.AlterField(
            model_name='nbabprmodelartifact',
            name='off_pipeline',
            field=models.BinaryField(help_text='Pickled sklearn Pipeline (StandardScaler + RidgeCV) for offense'),
        ),
    ]
