# Generated by Django 5.0.1 on 2026-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_add_prediction_sigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbamodelcalibration',
            name='ffi_raw_coef_efg',
            field=models.FloatField(blank=True, help_text='adj_net pts/100 poss per 1pp of eFG margin', null=True),
        ),
        migrations.AddField(
            model_name='nbamodelcalibration',
            name='ffi_raw_coef_fta',
            field=models.FloatField(blank=True, help_text='adj_net pts/100 poss per 1pp of FTA margin', null=True),
        ),
        migrations.AddField(
            model_name='nbamodelcalibration',
            name='ffi_raw_coef_oreb',
            field=models.FloatField(blank=True, help_text='adj_net pts/100 poss per 1pp of OREB edge', null=True),
        ),
        migrations.AddField(
            model_name='nbamodelcalibration',
            name='ffi_raw_coef_tov',
            field=models.FloatField(blank=True, help_text='adj_net pts/100 poss per 1pp of TOV edge', null=True),
        ),
        migrations.AddField(
            model_name='nbamodelcalibration',
            name='ffi_raw_intercept',
            field=models.FloatField(blank=True, help_text='OLS intercept from four-factors → adj_net regression', null=True),
        ),
    ]
