# Generated by Django 5.0.1 on 2026-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_add_game_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='career_bpr',
            field=models.FloatField(blank=True, help_text='Minutes-weighted career average BPR', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='peak_bpr',
            field=models.FloatField(blank=True, help_text='Best single-season BPR (≥500 min qualifier)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='wins_added',
            field=models.FloatField(blank=True, help_text='Wins above replacement player', null=True),
        ),
    ]
