# Generated by Django 5.0.1 on 2026-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0012_player_value_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbagame',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Game arena elevation in feet', null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Home arena elevation in feet', null=True),
        ),
    ]
