# Generated by Django 5.0.1 on 2026-06-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0013_nbagame_elevation_nbateam_elevation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAPlayerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(db_index=True, help_text='Date of the game this report applies to')),
                ('status', models.CharField(choices=[('available', 'Available'), ('probable', 'Probable'), ('day_to_day', 'Day-to-Day'), ('questionable', 'Questionable'), ('game_time_decision', 'Game-Time Decision'), ('doubtful', 'Doubtful'), ('out', 'Out'), ('out_for_season', 'Out for Season')], db_index=True, default='available', max_length=24)),
                ('injury_reason', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='espn', help_text='Data source slug (espn, nba_official, manual)', max_length=32)),
                ('report_timestamp', models.DateTimeField(blank=True, help_text='When the source reported this status', null=True)),
                ('expected_minutes_pct', models.FloatField(blank=True, help_text='Override minute share (null = use full mpg)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_reports', to='nba.nbaplayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_reports', to='nba.nbaseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_reports', to='nba.nbateam')),
            ],
            options={
                'ordering': ['game_date', 'team', 'player'],
                'indexes': [models.Index(fields=['team', 'game_date'], name='nba_nbaplay_team_id_c1eae4_idx'), models.Index(fields=['game_date', 'status'], name='nba_nbaplay_game_da_2ddb3d_idx')],
                'unique_together': {('player', 'game_date', 'source')},
            },
        ),
    ]
