# Generated by Django 5.0.1 on 2026-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0014_nbaplayeravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="nbateamseasonratings",
            name="conference_seed",
            field=models.IntegerField(
                blank=True,
                help_text="Regular-season conference rank (1-15) from compute_standings()",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nbateamseasonratings",
            name="playoff_finish",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Champion", "Champion"),
                    ("Runner-Up", "Runner-Up"),
                    ("Conf Finals", "Conference Finals"),
                    ("Conf Semis", "Conference Semifinals"),
                    ("Round 1", "First Round"),
                ],
                help_text="Playoff finish (null if missed playoffs)",
                max_length=20,
                null=True,
            ),
        ),
    ]
