# Generated by Django 5.0.1 on 2026-06-23 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0015_nbateamseasonratings_conference_seed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSeasonOutlook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("team_abbr", models.CharField(max_length=5)),
                ("team_slug", models.SlugField(unique=True)),
                (
                    "conference",
                    models.CharField(
                        choices=[("East", "Eastern Conference"), ("West", "Western Conference")],
                        max_length=10,
                    ),
                ),
                ("primary_color", models.CharField(default="#000000", max_length=7)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("wins", models.IntegerField(blank=True, null=True)),
                ("losses", models.IntegerField(blank=True, null=True)),
                ("adj_offensive_rating", models.FloatField(blank=True, null=True)),
                ("adj_defensive_rating", models.FloatField(blank=True, null=True)),
                ("adj_net_rating", models.FloatField(blank=True, null=True)),
                ("ffi", models.FloatField(blank=True, null=True)),
                ("efg_pct", models.FloatField(blank=True, null=True)),
                ("opp_efg_pct", models.FloatField(blank=True, null=True)),
                ("tov_pct", models.FloatField(blank=True, null=True)),
                ("opp_tov_pct", models.FloatField(blank=True, null=True)),
                ("oreb_pct", models.FloatField(blank=True, null=True)),
                ("opp_oreb_pct", models.FloatField(blank=True, null=True)),
                ("fta_rate", models.FloatField(blank=True, null=True)),
                ("opp_fta_rate", models.FloatField(blank=True, null=True)),
                ("pace", models.FloatField(blank=True, null=True)),
                ("projected_wins", models.IntegerField(blank=True, null=True)),
                ("projected_losses", models.IntegerField(blank=True, null=True)),
                ("projected_adj_net", models.FloatField(blank=True, null=True)),
                (
                    "outlook_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("title_contender", "Title Contender"),
                            ("playoff_contender", "Playoff Contender"),
                            ("bubble", "Bubble Team"),
                            ("lottery", "Lottery Team"),
                            ("rebuilding", "Rebuilding"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("season_headline", models.CharField(blank=True, max_length=200)),
                ("macfax_take", models.TextField(blank=True)),
                ("development_spotlight_player", models.CharField(blank=True, max_length=100)),
                ("development_spotlight_text", models.TextField(blank=True)),
                ("season_defining_variable", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-adj_net_rating"],
            },
        ),
        migrations.CreateModel(
            name="TeamOutseasonMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("signed", "Free Agent Signed"),
                            ("lost", "Free Agent Lost"),
                            ("drafted", "Drafted"),
                            ("traded_in", "Acquired via Trade"),
                            ("traded_out", "Traded Away"),
                            ("extended", "Extension Signed"),
                            ("waived", "Waived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("detail", models.CharField(blank=True, max_length=200)),
                (
                    "impact_rating",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offseason_moves",
                        to="nba.teamseasonoutlook",
                    ),
                ),
            ],
            options={
                "ordering": ["-impact_rating", "move_type"],
            },
        ),
        migrations.CreateModel(
            name="ProjectedStarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.CharField(max_length=5)),
                ("player_name", models.CharField(max_length=100)),
                ("position_order", models.IntegerField(default=0, help_text="1-5 display order")),
                ("role_note", models.CharField(blank=True, max_length=200)),
                ("bpr_rating", models.FloatField(blank=True, null=True)),
                ("key_question", models.CharField(blank=True, max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projected_starters",
                        to="nba.teamseasonoutlook",
                    ),
                ),
            ],
            options={
                "ordering": ["position_order"],
            },
        ),
    ]
