# Generated by Django 5.0.1 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0016_teamseasonoutlook_teamoutseasonmove_projectedstarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="nbaplayergamestats",
            name="oreb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nbaplayergamestats",
            name="dreb",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
