# Generated by Django 5.0.1 on 2026-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0018_nba_team_outlook_projections"),
    ]

    operations = [
        migrations.AddField(
            model_name="nbaplayer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
