# Generated by Django 5.0.1 on 2026-07-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0021_teamoutseasonmove_mps_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='projection_alpha',
            field=models.FloatField(blank=True, help_text='Blend weight on z(BPR)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='projection_value',
            field=models.FloatField(blank=True, help_text='Team-forecast player input (z-scored blend; see docs/bpr_audit/09)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='projection_value_source',
            field=models.CharField(blank=True, help_text='bpr+bpm | bpr_only (no BPM match)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nbaplayerseasonstats',
            name='projection_value_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
