# Generated by Django 5.0.1 on 2026-07-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0022_nbaplayerseasonstats_projection_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaprojectedrosterslot',
            name='computed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nbaprojectedrosterslot',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', help_text='PIPELINE_VERSION of compute_nba_team_outlooks that wrote this row', max_length=20),
        ),
        migrations.AddField(
            model_name='teamseasonoutlook',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', help_text='PIPELINE_VERSION of compute_nba_team_outlooks that last wrote projections', max_length=20),
        ),
    ]
