# Generated by Django 5.0.1 on 2026-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0023_nbaprojectedrosterslot_computed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaprojectedrosterslot',
            name='projected_minutes_share',
            field=models.FloatField(blank=True, help_text='Share of the 5.0-slot minutes pool (0–1.8); 1.0 = 20% of team minutes = ~9.6 MPG-equivalent at 48min', null=True),
        ),
    ]
