# Generated by Django 5.0.1 on 2026-07-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0024_alter_nbaprojectedrosterslot_projected_minutes_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamoutseasonmove",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Target season this offseason move applies to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outseason_moves",
                to="nba.nbaseason",
            ),
        ),
        migrations.AddField(
            model_name="teamoutseasonmove",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual entry"),
                    ("sync", "Roster sync"),
                    ("trade_pair", "Trade-pair inference"),
                    ("draft", "Draft import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teamoutseasonmove",
            name="transaction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamseasonoutlook",
            name="projected_seed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamseasonoutlook",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Projected (target) season this outlook row versions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_outlooks",
                to="nba.nbaseason",
            ),
        ),
        migrations.AddField(
            model_name="teamseasonoutlook",
            name="seed_distribution",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamseasonoutlook",
            name="snapshot_frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teamseasonoutlook",
            name="team_slug",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="teamseasonoutlook",
            constraint=models.UniqueConstraint(
                fields=("team_slug", "season"), name="uniq_team_outlook_slug_season"
            ),
        ),
    ]
