# Generated by Django 5.0.1 on 2026-07-24 15:57

from django.db import migrations, models


def publish_current(apps, schema_editor):
    """
    The rows that exist at migration time back the live public page — mark the
    single existing season published so the page keeps serving after the view
    starts filtering on is_published. If more than one season is already present
    (unexpected here), publish only the newest and leave older seasons dark.
    """
    NBASeason = apps.get_model("nba", "NBASeason")
    TeamSeasonOutlook = apps.get_model("nba", "TeamSeasonOutlook")
    seasons = list(
        TeamSeasonOutlook.objects.values_list("season__year", flat=True).distinct()
    )
    seasons = [y for y in seasons if y is not None]
    if not seasons:
        return
    newest = max(seasons)
    TeamSeasonOutlook.objects.filter(season__year=newest).update(is_published=True)


def unpublish_all(apps, schema_editor):
    TeamSeasonOutlook = apps.get_model("nba", "TeamSeasonOutlook")
    TeamSeasonOutlook.objects.update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0027_outlook_season_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamseasonoutlook",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(publish_current, unpublish_all),
    ]
