# Generated by Django 5.0.1 on 2026-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0028_outlook_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='draft_overall_pick',
            field=models.IntegerField(blank=True, help_text='NBA.com DraftHistory overall pick (null = undrafted/unknown)', null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer',
            name='draft_year',
            field=models.IntegerField(blank=True, help_text='Draft SEASON year from NBA.com DraftHistory (entered NBA year+1)', null=True),
        ),
    ]
