# Generated by Django 5.0.1 on 2026-02-12 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ending year (2026 for 2025-26 season)', unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=20)),
                ('is_current', models.BooleanField(default=False, help_text='Is this the active season?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=20)),
                ('teams_ingested', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, help_text='Overall rank', null=True)),
                ('rank_adj_em', models.IntegerField(blank=True, null=True)),
                ('rank_adj_o', models.IntegerField(blank=True, null=True)),
                ('rank_adj_d', models.IntegerField(blank=True, null=True)),
                ('adj_em', models.FloatField(help_text='Adjusted Efficiency Margin')),
                ('adj_o', models.FloatField(help_text='Adjusted Offensive Efficiency')),
                ('adj_d', models.FloatField(help_text='Adjusted Defensive Efficiency')),
                ('adj_tempo', models.FloatField(help_text='Adjusted Tempo')),
                ('efg_pct', models.FloatField(help_text='Effective FG%')),
                ('tov_pct', models.FloatField(help_text='Turnover %')),
                ('orb_pct', models.FloatField(help_text='Offensive Rebound %')),
                ('ftr', models.FloatField(help_text='Free Throw Rate')),
                ('efg_pct_d', models.FloatField(help_text='Opponent Effective FG%')),
                ('tov_pct_d', models.FloatField(help_text='Opponent Turnover %')),
                ('drb_pct', models.FloatField(help_text='Defensive Rebound %')),
                ('ftr_d', models.FloatField(help_text='Opponent Free Throw Rate')),
                ('fg2_pct', models.FloatField(blank=True, help_text='2-point FG%', null=True)),
                ('fg2_pct_d', models.FloatField(blank=True, help_text='Opponent 2-point FG%', null=True)),
                ('fg3_pct', models.FloatField(blank=True, help_text='3-point FG%', null=True)),
                ('fg3_pct_d', models.FloatField(blank=True, help_text='Opponent 3-point FG%', null=True)),
                ('fg3_rate', models.FloatField(blank=True, help_text='3-point attempt rate', null=True)),
                ('fg3_rate_d', models.FloatField(blank=True, help_text='Opponent 3-point attempt rate', null=True)),
                ('wab', models.FloatField(blank=True, help_text='Wins Above Bubble', null=True)),
                ('sor', models.FloatField(blank=True, help_text='Strength of Record', null=True)),
                ('barthag', models.FloatField(blank=True, help_text='Barthag win probability', null=True)),
                ('luck', models.FloatField(blank=True, help_text='Luck rating', null=True)),
                ('sos_adj_em', models.FloatField(blank=True, help_text='Strength of Schedule (AdjEM)', null=True)),
                ('ncsos_adj_em', models.FloatField(blank=True, help_text='Non-conference SOS (AdjEM)', null=True)),
                ('efg_margin', models.FloatField(default=0, help_text='eFG% - Opp eFG%')),
                ('tov_edge', models.FloatField(default=0, help_text='Opp TOV% - TOV%')),
                ('reb_edge', models.FloatField(default=0, help_text='ORB% - (100 - DRB%)')),
                ('ftr_margin', models.FloatField(default=0, help_text='FTR - Opp FTR')),
                ('has_kenpom', models.BooleanField(default=False)),
                ('has_torvik', models.BooleanField(default=False)),
                ('has_cbb_analytics', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conference')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='core.team')),
            ],
            options={
                'verbose_name_plural': 'Team Season Stats',
                'ordering': ['season', 'rank'],
                'indexes': [models.Index(fields=['season', 'rank'], name='core_teamse_season__0d2d3c_idx'), models.Index(fields=['season', 'conference'], name='core_teamse_season__c23e63_idx'), models.Index(fields=['season', 'adj_em'], name='core_teamse_season__f45880_idx')],
                'unique_together': {('team', 'season')},
            },
        ),
    ]
