# Generated by Django 5.0.1 on 2026-02-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nationalaverages'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_drb_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Defensive Rebound %'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_efg_margin',
            field=models.FloatField(default=0.0, help_text='Adjusted eFG margin'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_efg_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Effective FG%'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_ftr',
            field=models.FloatField(default=0.0, help_text='Adjusted Free Throw Rate'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_ftr_margin',
            field=models.FloatField(default=0.0, help_text='Adjusted FTR margin'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_opp_efg_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Opponent eFG%'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_opp_ftr',
            field=models.FloatField(default=0.0, help_text='Adjusted Opponent FTR'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_opp_tov_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Opponent TOV%'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_orb_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Offensive Rebound %'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_reb_edge',
            field=models.FloatField(default=0.0, help_text='Adjusted REB edge'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_tov_edge',
            field=models.FloatField(default=0.0, help_text='Adjusted TOV edge'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='adj_tov_pct',
            field=models.FloatField(default=0.0, help_text='Adjusted Turnover %'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='ffi_adj',
            field=models.FloatField(default=50.0, help_text='Four Factor Index (from adjusted margins, 0-100 scale)'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='ffi_raw',
            field=models.FloatField(default=50.0, help_text='Four Factor Index (from raw margins, 0-100 scale)'),
        ),
    ]
