# Generated by Django 5.0.1 on 2026-02-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team_is_d1'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonratings',
            name='d1_games_played',
            field=models.IntegerField(default=0, help_text='Games vs D1 opponents only'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='losses',
            field=models.IntegerField(default=0, help_text='Total losses (all opponents)'),
        ),
        migrations.AddField(
            model_name='teamseasonratings',
            name='wins',
            field=models.IntegerField(default=0, help_text='Total wins (all opponents)'),
        ),
        migrations.AlterField(
            model_name='teamseasonratings',
            name='games_played',
            field=models.IntegerField(default=0, help_text='Total games played (all opponents)'),
        ),
    ]
