# Generated by Django 5.0.1 on 2026-03-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_core_datapr_job_id_idx_core_datapr_job_id_68473b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasonratings',
            name='adj_d',
            field=models.FloatField(default=0.0, help_text='Adjusted Defensive Rating'),
        ),
        migrations.AlterField(
            model_name='teamseasonratings',
            name='adj_em',
            field=models.FloatField(default=0.0, help_text='Adjusted Net Rating (O - D)'),
        ),
        migrations.AlterField(
            model_name='teamseasonratings',
            name='adj_o',
            field=models.FloatField(default=0.0, help_text='Adjusted Offensive Rating'),
        ),
        migrations.AlterField(
            model_name='teamseasonratings',
            name='adj_tempo',
            field=models.FloatField(default=0.0, help_text='Adjusted Tempo (possessions per game)'),
        ),
    ]
