# Generated by Django 5.0.1 on 2026-03-03 17:18

from django.db import migrations
import yaml
from pathlib import Path


def load_ncaa_mappings(apps, schema_editor):
    """Load NCAA team name mappings from YAML and add as aliases."""
    Team = apps.get_model('core', 'Team')
    
    # Read the YAML file
    yaml_path = Path(__file__).resolve().parent.parent.parent / 'ncaa_team_name_mappings.yml'
    
    if not yaml_path.exists():
        print(f"Warning: {yaml_path} not found, skipping NCAA mapping load")
        return
    
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)
    
    mappings = data.get('ncaa', {})
    
    # For each NCAA name -> Database name mapping
    for ncaa_name, db_name in mappings.items():
        try:
            # Find team by name (exact match on the database name)
            team = Team.objects.get(name=db_name)
            
            # Add NCAA name to aliases if not already present
            if ncaa_name not in team.aliases:
                team.aliases.append(ncaa_name)
                team.save()
        except Team.DoesNotExist:
            print(f"Warning: No team found for '{db_name}' (NCAA: '{ncaa_name}')")
        except Exception as e:
            print(f"Error processing '{ncaa_name}' -> '{db_name}': {e}")


def reverse_ncaa_mappings(apps, schema_editor):
    """Reverse: remove NCAA names from team aliases."""
    Team = apps.get_model('core', 'Team')
    
    # Read the YAML file
    yaml_path = Path(__file__).resolve().parent.parent.parent / 'ncaa_team_name_mappings.yml'
    
    if not yaml_path.exists():
        return
    
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)
    
    mappings = data.get('ncaa', {})
    ncaa_names = set(mappings.keys())
    
    # Remove NCAA names from all team aliases
    for team in Team.objects.all():
        team.aliases = [alias for alias in team.aliases if alias not in ncaa_names]
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_teamseasonratings_adj_d_and_more'),
    ]

    operations = [
        migrations.RunPython(load_ncaa_mappings, reverse_ncaa_mappings),
    ]
