# Generated by Django 5.0.1 on 2026-04-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_projection_phase2_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRosterFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected_season_year', models.IntegerField(help_text='Season year being projected to (e.g. 2027 if from_season.year=2026)')),
                ('n_players', models.IntegerField(default=0, help_text='Number of players included in this fit computation')),
                ('overall_fit_score', models.FloatField(blank=True, null=True)),
                ('offensive_fit_score', models.FloatField(blank=True, null=True)),
                ('defensive_fit_score', models.FloatField(blank=True, null=True)),
                ('creation_fit', models.FloatField(blank=True, null=True)),
                ('shooting_fit', models.FloatField(blank=True, null=True)),
                ('ball_security_fit', models.FloatField(blank=True, null=True)),
                ('finishing_fit', models.FloatField(blank=True, null=True)),
                ('pressure_fit', models.FloatField(blank=True, null=True)),
                ('off_rebounding_fit', models.FloatField(blank=True, null=True)),
                ('role_balance_off_fit', models.FloatField(blank=True, null=True)),
                ('off_total_penalty', models.FloatField(blank=True, null=True)),
                ('rim_protection_fit', models.FloatField(blank=True, null=True)),
                ('def_rebounding_fit', models.FloatField(blank=True, null=True)),
                ('disruption_fit', models.FloatField(blank=True, null=True)),
                ('foul_discipline_fit', models.FloatField(blank=True, null=True)),
                ('perimeter_defense_fit', models.FloatField(blank=True, null=True)),
                ('size_coverage_fit', models.FloatField(blank=True, null=True)),
                ('mobility_fit', models.FloatField(blank=True, null=True)),
                ('role_balance_def_fit', models.FloatField(blank=True, null=True)),
                ('def_total_penalty', models.FloatField(blank=True, null=True)),
                ('off_penalties', models.JSONField(blank=True, help_text='List of [label, pts] offensive structural penalties', null=True)),
                ('def_penalties', models.JSONField(blank=True, help_text='List of [label, pts] defensive structural penalties', null=True)),
                ('offensive_strengths', models.JSONField(blank=True, help_text='Top offensive subcomponent names', null=True)),
                ('offensive_weaknesses', models.JSONField(blank=True, null=True)),
                ('defensive_strengths', models.JSONField(blank=True, null=True)),
                ('defensive_weaknesses', models.JSONField(blank=True, null=True)),
                ('fit_summary', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='playerseasonprojection',
            new_name='core_player_from_se_442377_idx',
            old_name='core_playerse_from_se_idx',
        ),
        migrations.RenameIndex(
            model_name='playerseasonprojection',
            new_name='core_player_player__67cd34_idx',
            old_name='core_playerse_player_idx',
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='assumptions',
            field=models.JSONField(blank=True, help_text='Documented BPR article deviations', null=True),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='coefficients',
            field=models.JSONField(default=list, help_text='Trained coefficients aligned to feature_names'),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='cv_metrics',
            field=models.JSONField(blank=True, help_text='{rmse, r2, best_alpha, fold_rmses}', null=True),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='feature_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='intercept',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='model_type',
            field=models.CharField(help_text='box_off | box_def | rapm_baseline | rapm_informed', max_length=32),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='n_observations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='n_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bprmodelartifact',
            name='regularization_alpha',
            field=models.FloatField(blank=True, help_text='Ridge lambda chosen by CV', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonprojection',
            name='minutes_overridden',
            field=models.BooleanField(default=False, help_text="True when this player's minutes share was manually pinned via a sandbox override.  Always False for baseline (non‑scenario) runs."),
        ),
        migrations.AlterField(
            model_name='playerseasonprojection',
            name='minutes_share_p2',
            field=models.FloatField(blank=True, help_text='Phase 2 projected minutes share (mpg / 40) from the roster‑context allocator.  Sums to 5.00 across all players on the same team.  Replaces the Phase 1 baseline (projected_minutes_share) for roster work.', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonprojection',
            name='role_bucket',
            field=models.CharField(blank=True, choices=[('G', 'Guard'), ('Wing', 'Wing'), ('Big', 'Big')], help_text='Role bucket derived from Player.position, with box‑score rates as fallback for ambiguous positions (ATH, NA, empty).  G = Guard, Wing = Forward/Wing, Big = Center/Power Forward.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonprojection',
            name='rotation_rank',
            field=models.IntegerField(blank=True, help_text="Rotation rank within the player's team (1 = highest projected minutes).  Computed by the Phase 2 minutes allocator.", null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonprojection',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Canonical team for this projection — the team with the most possessions logged by this player in from_season.  For single-team players this is their only team.  For split-season players this is the team they logged the most court time with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_projections', to='core.team'),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='adj_team_def_eff_on',
            field=models.FloatField(blank=True, help_text='Team adj def eff (pts/100 poss) while player on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='adj_team_off_eff_on',
            field=models.FloatField(blank=True, help_text='Team adj off eff (pts/100 poss) while player on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='box_bpr',
            field=models.FloatField(blank=True, help_text='Box BPR = box_obpr + box_dbpr', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='box_dbpr',
            field=models.FloatField(blank=True, help_text='Defensive Box BPR (box-score model)', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='box_obpr',
            field=models.FloatField(blank=True, help_text='Offensive Box BPR (box-score model)*', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='bpr',
            field=models.FloatField(blank=True, help_text='Bayesian Performance Rating = OBPR + DBPR', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='bpr_last_updated',
            field=models.DateTimeField(blank=True, help_text='When BPR was last computed', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='bpr_model_version',
            field=models.CharField(blank=True, help_text='BPR model version tag', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='dbpr',
            field=models.FloatField(blank=True, help_text='Defensive BPR: pts/100 poss better than D1 avg on defense', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='dbpr_source',
            field=models.CharField(blank=True, help_text="Source of DBPR: 'rapm', 'box_bpr', or null", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='def_poss',
            field=models.FloatField(blank=True, help_text='Estimated defensive possessions while on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='obpr',
            field=models.FloatField(blank=True, help_text='Offensive BPR: pts/100 poss above D1 avg on offense', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='obpr_source',
            field=models.CharField(blank=True, help_text="Source of OBPR: 'rapm', 'box_bpr', or null", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='off_poss',
            field=models.FloatField(blank=True, help_text='Estimated offensive possessions while on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_drb_pct',
            field=models.FloatField(blank=True, help_text='Team DRB% (opp ORB%) while on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_efg_margin',
            field=models.FloatField(blank=True, help_text='eFG% margin while on', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_ffi',
            field=models.FloatField(blank=True, help_text='Four Factor Index (0-100) while on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_ftr_margin',
            field=models.FloatField(blank=True, help_text='FTR margin while on', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_opp_tov_pct',
            field=models.FloatField(blank=True, help_text='Opp TOV% while on court', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_reb_edge',
            field=models.FloatField(blank=True, help_text='Rebound edge while on', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='on_court_tov_edge',
            field=models.FloatField(blank=True, help_text='TOV edge while on', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='preseason_obpr',
            field=models.FloatField(blank=True, help_text='Preseason estimated OBPR', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='prior_mean_dbpr',
            field=models.FloatField(blank=True, help_text='Prior mean for DBPR in Bayesian RAPM', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='prior_mean_obpr',
            field=models.FloatField(blank=True, help_text='Prior mean for OBPR in Bayesian RAPM', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='prior_sd_dbpr',
            field=models.FloatField(blank=True, help_text='Prior SD for DBPR', null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstats',
            name='prior_sd_obpr',
            field=models.FloatField(blank=True, help_text='Prior SD for OBPR', null=True),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='from_season',
            field=models.ForeignKey(help_text='The season the projection is based on (Phase 1 source season)', on_delete=django.db.models.deletion.CASCADE, related_name='team_roster_fits', to='core.season'),
        ),
        migrations.AddField(
            model_name='teamrosterfit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_fits', to='core.team'),
        ),
        migrations.AddIndex(
            model_name='teamrosterfit',
            index=models.Index(fields=['from_season', 'projected_season_year'], name='core_teamro_from_se_d2158c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrosterfit',
            index=models.Index(fields=['team', 'from_season'], name='core_teamro_team_id_27cfba_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamrosterfit',
            constraint=models.UniqueConstraint(fields=('team', 'from_season'), name='unique_team_season_fit'),
        ),
    ]
