# Generated by Django 5.0.1 on 2026-04-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_phase4_contextual_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected_season_year', models.IntegerField(help_text='Calendar year of the season being projected (from_season.year + 1)')),
                ('base_team_offense', models.FloatField(blank=True, help_text='Σ(minutes_share_p2 × projected_obpr); weighted offensive BPR', null=True)),
                ('base_team_defense', models.FloatField(blank=True, help_text='Σ(minutes_share_p2 × projected_dbpr); weighted defensive BPR', null=True)),
                ('base_team_roster_strength', models.FloatField(blank=True, help_text='Σ(minutes_share_p2 × projected_bpr); weighted total BPR', null=True)),
                ('returner_minutes_fraction', models.FloatField(blank=True, help_text='Fraction (0-1) of projected minutes allocated to returners', null=True)),
                ('continuity_score', models.FloatField(blank=True, help_text='returner_minutes_fraction × 100; 0-100 continuity index', null=True)),
                ('continuity_adjustment_off', models.FloatField(blank=True, help_text='Continuity bonus applied to projected_adj_o (pts/100 poss)', null=True)),
                ('continuity_adjustment_def', models.FloatField(blank=True, help_text='Continuity bonus applied to projected_adj_d (subtracted; positive = improvement)', null=True)),
                ('fit_adjustment_off', models.FloatField(blank=True, help_text='Phase 3+4 fit bonus applied to projected_adj_o (pts/100 poss)', null=True)),
                ('fit_adjustment_def', models.FloatField(blank=True, help_text='Phase 3+4 fit bonus applied to projected_adj_d (pts/100 poss; positive = improvement)', null=True)),
                ('coaching_continuity_adjustment', models.FloatField(default=0.0, help_text='Coaching-continuity adjustment (always 0.0 — no coach data available)')),
                ('projected_adj_o', models.FloatField(blank=True, help_text='Projected adjusted tempo-free offensive efficiency (pts/100 poss)', null=True)),
                ('projected_adj_d', models.FloatField(blank=True, help_text='Projected adjusted tempo-free defensive efficiency (pts/100 poss; lower = better)', null=True)),
                ('projected_adj_em', models.FloatField(blank=True, help_text='projected_adj_o − projected_adj_d', null=True)),
                ('team_projection_uncertainty', models.FloatField(blank=True, help_text='0-1 uncertainty score; 0 = high confidence, 1 = low confidence', null=True)),
                ('projected_adj_o_low', models.FloatField(blank=True, help_text='Lower bound of projected_adj_o confidence band (−1σ)', null=True)),
                ('projected_adj_o_high', models.FloatField(blank=True, help_text='Upper bound of projected_adj_o confidence band (+1σ)', null=True)),
                ('projected_adj_d_low', models.FloatField(blank=True, help_text='Lower bound of projected_adj_d confidence band (numerically lower = better defense)', null=True)),
                ('projected_adj_d_high', models.FloatField(blank=True, help_text='Upper bound of projected_adj_d confidence band', null=True)),
                ('projected_adj_em_low', models.FloatField(blank=True, help_text='Lower bound of projected_adj_em confidence band (−2σ)', null=True)),
                ('projected_adj_em_high', models.FloatField(blank=True, help_text='Upper bound of projected_adj_em confidence band (+2σ)', null=True)),
                ('projected_national_rank', models.IntegerField(blank=True, help_text='Projected national rank by adj_em (1 = best)', null=True)),
                ('projected_offense_rank', models.IntegerField(blank=True, help_text='Projected rank by adj_o (1 = highest offensive efficiency)', null=True)),
                ('projected_defense_rank', models.IntegerField(blank=True, help_text='Projected rank by adj_d (1 = lowest / best defensive efficiency)', null=True)),
                ('national_rank_range_low', models.IntegerField(blank=True, help_text='Most optimistic (lowest number = best) national rank from uncertainty band', null=True)),
                ('national_rank_range_high', models.IntegerField(blank=True, help_text='Most pessimistic (highest number = worst) national rank from uncertainty band', null=True)),
                ('offense_rank_range_low', models.IntegerField(blank=True, help_text='Most optimistic offense rank', null=True)),
                ('offense_rank_range_high', models.IntegerField(blank=True, help_text='Most pessimistic offense rank', null=True)),
                ('defense_rank_range_low', models.IntegerField(blank=True, help_text='Most optimistic defense rank', null=True)),
                ('defense_rank_range_high', models.IntegerField(blank=True, help_text='Most pessimistic defense rank', null=True)),
                ('projection_summary', models.JSONField(default=dict, help_text='Compact projection summary dict for UI/API')),
                ('driver_breakdown', models.JSONField(default=list, help_text='Ordered list of adjustment driver dicts with magnitudes')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('from_season', models.ForeignKey(help_text='Season whose data (Phase 1-4) was used to build this projection', on_delete=django.db.models.deletion.CASCADE, related_name='team_projections', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_projections', to='core.team')),
            ],
            options={
                'indexes': [models.Index(fields=['from_season', 'projected_season_year'], name='core_teamse_from_se_329d84_idx'), models.Index(fields=['projected_adj_em'], name='core_teamse_project_02ab68_idx'), models.Index(fields=['team', 'from_season'], name='core_teamse_team_id_ad26ac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='teamseasonprojection',
            constraint=models.UniqueConstraint(fields=('team', 'from_season'), name='unique_team_season_projection'),
        ),
    ]
